### ISSUE TITLE
Selector tools' "remove from" overflows

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#1015]
The selector tools in the _remove stops_ and _adjust speed_ modifications both have an option to "Remove from" the current selection. In both cases it overflows it's div. 

![Screenshot_2020-02-04_15-46-45](https://user-images.githubusercontent.com/7830465/73785772-f66f9c00-4765-11ea-8bc4-de8e15b12308.png)

![segment-selector](https://user-images.githubusercontent.com/7830465/73785832-1d2dd280-4766-11ea-9215-d3be75d1e4a2.png)

Perhaps these could be styled as flex-boxes?

**Comment by ansoncfit** [comment]
Closed by #1150 (again, not sure why GH automation didn't work)
