### ISSUE TITLE
Segment speed scaled by 5x yet no "changes to transport network"?

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#1017]
I've created a [modification](https://analysis-staging.conveyal.com/regions/5e384f5f7a87c75dd52117d3/projects/5e385d1a7a87c75dd52118c0/modifications/5e39c5583f8927459fbfe8d0) of TriMet's WES commuter line, increasing the speed on the segment between Tualatin and Tigard stations. I was able to see some travel time improvements for southbound travel, but not northbound. I tried removing the southbound trip patterns, leaving only the northbound and selecting the same segment again just to make sure I did actually have it selected (see #1016). I increased the speed factor to 5x just to be sure. In analysis I get the following error:

![Screenshot_2020-02-04_23-41-02](https://user-images.githubusercontent.com/7830465/73812067-7c610680-47a9-11ea-9548-429951250453.png)

I haven't checked the actual GTFS but the TriMet website [indicates](https://trimet.org/schedules/w/t1203_1.htm) there should be service in my time window. And the segments look to be selected on the map and in the advanced settings where it shows two hops, presumably one for each northbound trip pattern.

This happens with both r5 4.7.0 and the latest build.

**Comment by abyrd** [comment]
The modification only affects a few segments in the middle of the northbound patterns. Maybe this has something to do with pickup/dropoff types for those stops in the selected patterns. Nate has verified that these selected patterns do stop at either end of the selected segments though.

**Comment by Nate-Wessel** [comment]
I'm not able to reproduce this error in the latest round of testing.
