### ISSUE TITLE
Aggregation area histogram not shown

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#1020]
Following the [instructions](http://docs.analysis.conveyal.com/en/latest/analysis/regional.html#measuring-aggregate-accessibility) in the documentation, I am not able to create an accessibility histogram for an aggregation area of a regional analysis. 
Steps:
1. display a regional analysis 
2. select an aggregation area (it shows on the map as expected)
3. select a weighting attribute
4. nothing happens. 

I tried in both Firefox and Chromium.

**Comment by ansoncfit** [comment]
Now showing.
