### ISSUE TITLE
Shapefile route alignment import creates timetables called "Timetable NaN"

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#1021]
This is a very minor issue. 
When importing routes via the shapefile import tool, the timetables generated for the new routes are called "Timetable NaN". It's not an actual problem, as the names don't really effect anything... but nonetheless that NaN doesn't quite inspire confidence. They should just be called "Default Timetable" or something simple like that.

**Comment by trevorgerhardt** [comment]
This has been fixed on staging
