### ISSUE TITLE
What scale is used in the cumulative accessibility plots?

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#1030]
In the cumulative accessibility plots in analysis mode, what scale is used for the Y axis? 

<img width="619" alt="analysis-stacked-percentile" src="https://user-images.githubusercontent.com/7830465/74177885-974bd480-4c08-11ea-9951-a0693b4958e8.png">

Square root? It would be helpful to note this in the docs and probably also to give a little bit of a discussion around interpreting these plots. I.e. give some examples of typical curves - flat, convex, concave - and what they say about the transit network / distribution of opportunities.

**Comment by ansoncfit** [comment]
https://github.com/conveyal/analysis-ui/blob/419b4942d04f3ea52b19cd2f03889c9e29dff101/lib/components/analysis/stacked-percentile.js#L37
