### ISSUE TITLE
Cannot clear from/to stop in reroute modifications

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#105]
When editing a reroute modification, once a from- or to-stop is selected it is impossible to clear that selection. This means that if you've made a complex reroute near the end of a route and then decide to actually move the terminus of the route, you can't.

However, I'm wondering whether the from-stop and to-stop are necessary at all. It may be possible to eliminate them from the editor and the modification messages. See #104.

**Comment by ansoncfit** [comment]
I've just run into this issue and can confirm it's frustrating.  You can actually drag the stops around so it looks like it should be valid (as noted in #104):

![image](https://user-images.githubusercontent.com/2173529/31105193-3ab97c12-a7b0-11e7-888c-afb8b221046d.png)

But when trying to do a single point analysis the UI shows a "script error" without further explanation.  The error in the console states (correctly) that "First stop in reroute is not fromStop!"

A quick fix would be to add a "clear" button next to the "select" from/to stop buttons.

Another suggestion would be to add a "make start of reroute" and "make end of reroute" tooltip that appears when a user clicks on a (green) stop that's part of the existing pattern, and show a warning ("Click a green stop to connect your reroute to an existing stop") in the editing panel until at least one of these was clicked.
