### ISSUE TITLE
Aggregation area upload fails

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#1059]
**Describe the bug**
When uploading a new aggregation area, a "fail to fetch" error appears.

Console:
```
Access to fetch at 'https://api.conveyal.com/api/region/5d92758437ed8104615d7fa2/aggregationArea' from origin 'https://analysis.conveyal.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
11124ce2027db0b9775732b0c51e4b5438a232f1.592d84133adea8397961.js:1 POST https://api.conveyal.com/api/region/5d92758437ed8104615d7fa2/aggregationArea net::ERR_FAILED
```

**Comment by ansoncfit** [comment]
This appears to have been a transient issue. The aggregation areas I tried to upload now show up.

**Comment by ansoncfit** [comment]
Just tried with @trevorgerhardt:

Using the NYC boros as an upload shapefile, we're seeing three separate problems:
- On staging, strange CORS error on first try, but upload available on refresh
- On staging, separate error on subsequent try, but upload available on refresh
- Locally, no error message, but upload failed

**Comment by trevorgerhardt** [comment]
While this behavior has been improved, it still fails on large datasets. The next step should be refactoring the upload process on the backend.

**Comment by trevorgerhardt** [comment]
See https://github.com/conveyal/analysis-internal/issues/137
