### ISSUE TITLE
possibility of use different map engine

### ISSUE THREAD

**Issue by arunaxp** [conveyal/analysis-ui#1071]
Hi,

This is not a bug,I just wanted to clarify is there any possibility to use different map engine (Map API) instead of using MapBox ?

**Comment by trevorgerhardt** [comment]
Not via configuration. You would need to edit the code directly.

**Comment by arunaxp** [comment]
Hi @trevorgerhardt 

Thank you for your quick response. Would be able to give me sample of doing that or some documentation ?

**Comment by brunetton** [comment]
+1

**Comment by trevorgerhardt** [comment]
It's not simple. The code depends on Leaflet and MapboxGL and makes assumptions that Mapbox will be used. We have no intention to support other map libraries and therefore do not intend to make changes to support them.
