### ISSUE TITLE
What are the map engines that we can use  instead of using MapBox ?

### ISSUE THREAD

**Issue by arunaxp** [conveyal/analysis-ui#1072]
Hi @trevorgerhardt 

Could you please tell me what are the different map engine (Map API) that we can use instead of using MapBox ?

**Comment by trevorgerhardt** [comment]
You can look at MapTiler (https://www.maptiler.com/).

Please stop opening issues that are not bugs in the application.

**Comment by arunaxp** [comment]
Sorry for opening an issue, I didn't see any other alternative way of contacting someone in the team
