### ISSUE TITLE
Bundle deletion warns unecessarily about broken projects

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#1078]
It is not possible to delete a bundle that has projects associated with it. Still, when deleting a bundle there is a warning in an alert dialogue that any associated projects will stop working. This may cause users to manually check for any associated projects first, which is something already being done for them.

**Comment by ansoncfit** [comment]
Resolved in https://github.com/conveyal/analysis-ui/pull/1031
