### ISSUE TITLE
Apply all modifications to new scenario?

### ISSUE THREAD

**Issue by MarcovanderLinden** [conveyal/analysis-ui#108]
currently when creating a new variant, all measures are off by default. I'd suggest a choice: either check all boxes or check none.

**Comment by abyrd** [comment]
Rather than making them all on or off by default, we should just have two buttons: include all modifications, or remove all modifications from the variant.

**Comment by MarcovanderLinden** [comment]
Thinking a little more, being able to copy a variant would help a lot as well

**Comment by Nate-Wessel** [comment]
I'm assuming "variants" became what are now "scenarios". The default behaviour now seems to be to include all modifications in a new scenario. See my suggestion in #964

**Comment by trevorgerhardt** [comment]
Added the ability to copy a scenario
