### ISSUE TITLE
Strange travel times reported outside of region

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#1086]
Analysis reports travel time ranges outside the defined region and well outside the the transit/street network. It's not clear what the times are based on and sometimes they are rendered strangely or are surprisingly low. 

![Screenshot_2020-05-06_10-03-40](https://user-images.githubusercontent.com/7830465/81186664-10956200-8f81-11ea-9f6f-9083c5c15368.png)

![Screenshot_2020-05-06_10-13-08](https://user-images.githubusercontent.com/7830465/81187716-661e3e80-8f82-11ea-8a4a-d3cc67430814.png)

I would expect something like this where travel times are seemingly off the chart:
![Screenshot_2020-05-06_10-07-41](https://user-images.githubusercontent.com/7830465/81187063-8dc0d700-8f81-11ea-8671-782c6afaec68.png)

Just a small distance away though, there are travel times again. 
![Screenshot_2020-05-06_10-09-17](https://user-images.githubusercontent.com/7830465/81187246-c95ba100-8f81-11ea-94b5-0954bda4e848.png)

This is using just the baseline scenario and is present in the production version.

**Comment by ansoncfit** [comment]
Closed by #1183 (not sure why the GH automation didn't work)
