### ISSUE TITLE
Color picker for isochrones

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#1088]
Several users have reported that it's hard to see the isochrones when giving presentations on a projector, and I've also seen this in practice. On certain projectors the isochrones can be pale enough to make it impossible to see. Any color we pick will look good in some places and bad in others.

Adding a color picker raises all sorts of issues with UI uniformity and conflicts. It would probably meet most users' needs to just add a text field in the "advanced" settings, which would be parsed as decimal or hex color codes, or even color names if automatically supported by the color parser library.

**Comment by Nate-Wessel** [comment]
It might go a long way to simply add a contrasting boundary line to the isochrone. When mapping something like this I generally add a thin border in the same color but with a slightly lower opacity. It makes it a lot easier to pick up the color transitions without totally washing out the basemap.
