### ISSUE TITLE
Two LODES job categories with only zero values

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#1101]
There are two categories in the importable LODES data that don't seem to have any values and/or only zero values. I had thought for a while that this was a trouble with very low values not showing up well on the map, but now that I've tried running an analysis with these I'm fairly convinced it's actually something wrong with the data itself. 

The two categories are:
Jobs at firms aged x to y
Jobs at firms with between x and y employees

All the other categories seem in general to have reasonable values and spatial distributions. 

I wonder if this is actually something that is only available in certain states? I tried looking at this in both Cincinnati (OH,KY) and Portland (OR,WA) test regions, both dev and production.

**Comment by Nate-Wessel** [comment]
See https://lehd.ces.census.gov/data/lodes/LODES7/LODESTechDoc7.3.pdf

This may be a problem with the vintage of the original data source. 
"And datasets for 2011-2015 contain further additional variables (Firm Age and Firm Size) on the WAC files.3,4 The data structure for all years of data has been expanded to include space for these new variables, but in earlier years these variables contain only zeroes."

**Comment by Nate-Wessel** [comment]
Note that these two categories comprise ten variables and are the *first* ten in the dropdown menu which is sorted alphabetically. I.e. the first ten variables listed from the LODES import are empty.

**Comment by ansoncfit** [comment]
Just discussed with @abyrd -- having the first ten variables show nothing on the map may generate bad impressions or support requests. I should address when updating to the most recent LODES vintage.
