### ISSUE TITLE
Ability to specify exact departure times for new routes

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#111]
In the Netherlands we are seeing accessibility analysis results jitter a bit due to the use of Monte Carlo schedule draws. One solution is to increase the number of draws. These analyses are already slow, but anecdotally increasing the number of draws doesn't hurt speed much. 

However we know that in the Netherlands timed transfers are very common and usually reliable. So ideally in the scenario editor we'd be able to specify the time after the hour that a new line or frequency-adjusted line passes through a chosen station. This only makes sense for lines whose frequencies are a factor of 60 minutes (2, 3, 4, 5, 6, 10, 12, 15, 20, or 30 minutes). So perhaps we can have a separate new scheduling widget that only lets you choose among these frequencies, as well as a minute after the hour.

Choosing those parameters wisely requires knowing when other lines pass through a station, so it would also be good to have pop-up info boxes in the editor: you click on a station or a group of stations and it shows you all the lines that pass through and the times they pass through (from the GTFS-API).

In terms of the modification messages to be produced by the editor, the com.conveyal.r5.analyst.scenario.AddTrips.PatternTimetable#firstDepartures field allows you to specify a list of exact departure times from the first stop in a line.

**Comment by mattwigway** [comment]
This now works in the interface but the r5 backend is crashing when we try it.
