### ISSUE TITLE
Add tooltip/explanation when multi-point button is disabled

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#1124]
The regional/"multi-point" button is disabled unless an isochrone is displayed; checking single-origin results is a verification step that helps avoid heavy computation for analyses with invalid settings.

I think we used to have a clearer explanation of this in the UI -- I handled two support requests about it today. We could hide the multi-point button, or add an explanation like "Fetch results for single point first. Multi-point analysis is disabled unless an isochrone is displayed."

**Comment by trevorgerhardt** [comment]
Added a title. Tooltips with disabled buttons do not work...
