### ISSUE TITLE
Show total number of opportunities in dataset

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#1125]
Opportunity datasets have a `totalOpportunities` property. Displaying this total when a dataset is selected on the opportunity datasest page would help with troubleshooting and certain analyses. Perhaps it makes sense to batch this update with planned changes to display other metadata (e.g. createdBy, createdAt) through the Resources panel.

**Comment by trevorgerhardt** [comment]
Closed in #1388
