### ISSUE TITLE
"travelTimePercentile" in custom profile request has no apparent effect

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#1128]
Changing it it doesn't update the slider and moving the slider doesn't update it. I can't see that changing the value has any effect.

**Comment by abyrd** [comment]
It looks like moving the slider does not affect travelTimePercentile or the percentiles array sent to the backend. This is apparently making it impossible to run regional analyses at percentiles other than the median.

**Comment by trevorgerhardt** [comment]
This issue was resolved in 9cc6bfb1fa1c42744f2ce6b0fba3659624de0b23
