### ISSUE TITLE
Custom profile request JSON retains deleted fields

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#1130]
If a property is deleted from the custom profile request JSON in the UI, it is apparently not deleted from the stored version. The deleted property reappears in the JSON text box. This can get messy when editing the name of a property, for example after making a typo. The property may be saved in several intermediate states as you edit its name, creating n copies of the property with slightly different names.

**Comment by ansoncfit** [comment]
See also #930

**Comment by trevorgerhardt** [comment]
Fixed in #1251
