### ISSUE TITLE
Mode selector buttons could appear more "clickable"

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#1136]
Minor UI note: with recent restyles, the mode selector buttons look slightly less like buttons. This isn't a problem for longtime users, who are used to clicking on them. 

But a new user recently shared the observation that it was not immediately apparent how to change modes, and the [relevant part of the user manual](http://docs.analysis.conveyal.com/en/dev/analysis/configuration.html#access-transit-and-egress-modes) is not explicit about clicking on the mode buttons. At the least, we should update the user manual.

**Comment by trevorgerhardt** [comment]
Mode selectors are much brighter now! So I think this could be checked off. 

Closed in #1251
