### ISSUE TITLE
Send arrays of destination pointsets, cutoffs, and percentiles for regional analyses

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#1154]
The current backend requires arrays of percentiles, cutoffs, and destination pointsets. We already send `percentiles` as an array, but currently the UI seems to always send [50] even if another value is chosen. 

We will also need to send arrays `destinationPointSetIds` and `cutoffsMinutes`. The old singular fields are now ignored, and can be removed from the requests sent to the backend.

The backend does a checkNotNull on these three fields and will throw an exception if they are not present.

**Comment by trevorgerhardt** [comment]
This was fixed here: https://github.com/conveyal/analysis-ui/pull/1121/commits/f75a58106878d713cb2782d460b7f7d2f555a1ea

That should be on `dev` soon. It was just merged in.

**Comment by abyrd** [comment]
Thanks. I'll close the issue once I get a chance to test it out.

**Comment by abyrd** [comment]
Will this overwrite any values in the custom request JSON? If possible, it would be very useful to retain the possibility of sending an array of percentiles, cutoffs, or destination pointsets via the custom JSON.

**Comment by trevorgerhardt** [comment]
It only sets the values if they do not exist. You can set values via custom JSON.

**Comment by abyrd** [comment]
Using the version at https://analysis-staging.conveyal.com I'm unable to produce a regional analysis with a percentile other than 50.
