### ISSUE TITLE
Auto-create stops option available but not ckeckable until route drawn

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#1161]
In the add trip pattern modification, the option to "auto-create stops at set spacing" is available, but not editable until a route is actually drawn on the map. This is in contrast to the "bidirectional" option right below it which can be modified any time. If a null route can be bidirectional, it should probably be able to have a stop generator too. 

Either: 
* both options should be available and modifiable or 
* neither should be shown except in editing mode

This is in both production and staging.

**Comment by trevorgerhardt** [comment]
Fixed in #1190
