### ISSUE TITLE
Make it harder to close modal with stray click

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#1180]
When editing the list of cutoffs/percentiles for a regional analysis, I often highlight the list. But ending my click and drag outside the modal closes it.

The modal should only close when the click is initiated outside the modal, or when the close button is clicked.

**Comment by trevorgerhardt** [comment]
The Chakra UI component handles that. It appears to have been updated in the latest version: https://next.chakra-ui.com/docs/components/modal

**Comment by trevorgerhardt** [comment]
Or, we can just add `closeOnOverlayClick={false}` to the modal: https://chakra-ui.com/modal#close-modal-on-overlay-click

**Comment by trevorgerhardt** [comment]
Fixed in #1244
