### ISSUE TITLE
Modification visibility on map cannot be toggled

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#1217]
**Describe the bug**
After a modification is drawn or edited, its visibility icon in the modification list only works if the modification was exited by clicking on the back arrow at the top of the panel. If the user navigates away from the modification another way (e.g. clicking on the analysis tab), the modification won't be shown on the map even if the visibility icon for it or its scenario is clicked.

**To Reproduce**

1. Draw an add trip modification
2. Click on the analyze tab
3. Click on the modifications tab
4. Click the visibility icon to attempt to show the added route

**Comment by trevorgerhardt** [comment]
Closed in #1243
