### ISSUE TITLE
Region selection page not scrollable

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#1254]
If you navigate to the region selection page by clicking the globe icon, the page is not scrollable. If you reload the page or navigate to it by URL, it is scrollable.

**Comment by trevorgerhardt** [comment]
Hmm. I was not able to reproduce this. Did any errors occur ahead of navigating back to the page?

**Comment by abyrd** [comment]
If I remember right both @ansoncfit and I observed this problem, but it seems to be working now in `decay-funk` branch. I can't reproduce it, so closing.
