### ISSUE TITLE
Toasts accumulate when UI cannot contact backend

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#1266]
This happens when staging shuts down; not sure if it would happen under any normal circumstances for end-users:

![image](https://user-images.githubusercontent.com/2173529/95042092-c7b81580-06a6-11eb-8170-d64847cc0fe0.png)

**Comment by trevorgerhardt** [comment]
That is annoying. I think it would be pretty easy to track if the error toast is active and just show unique toasts.
