### ISSUE TITLE
Single/multi percentile no longer needed

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#1285]
We could get rid of the somewhat confusing "50 single point, 49 multi-point" label and lock the slider to only our 5 standard percentiles. Other percentiles are now specified directly in the dialog for creating a regional analysis. Even for older workers, specific percentiles can be specified in the regional analysis dialog.

**Comment by trevorgerhardt** [comment]
Yea, I was thinking about this. What type of input should we use for this? A slider is probably the wrong type of component for an input with five static values... 

Also, if we end up moving the opportunity selectors into the request settings that whole results row could change.

**Comment by abyrd** [comment]
To me, as with the travel time cutoff, the most important characteristic of these inputs is the ability to see the results change interactively while moving them. This is the way I usually use them: run an analysis, then slide the travel time back and forth, and slide the percentile down to 5, up, and back to the median, watching how the isochrones and reported travel times react. This gives valuable insights into whether the modifications are modeled correctly, how lines and headways interact with one another, etc. So if someone wants to quickly flip through all 5 percentiles and back to the median, and do that at several different origin points, having a UI element like a dropdown will require roughly two actions per percentile (click-drag-release), giving a sequence of 10 separate actions to be taken in order at each origin point. This is for something that with a slider, I'll casually do with a single movement as I'm thinking about the meaning of the results.

To me, this immediate interactive response is a defining characteristic of our system. So any UI element that had that ability would be a candidate. For example, a single number that can be dragged up and down. But that would basically be exactly the same as slider behavior, without the same graphical representation.

**Comment by trevorgerhardt** [comment]
I want to head away from that defining characteristic. Holding on to interactivity may be preventing us from seeing a better way of representing the information statically.

**Comment by trevorgerhardt** [comment]
Example to try: generate isochrones per cutoff a the same time all with a 20% opacity.

**Comment by trevorgerhardt** [comment]
Remember: sliders = bad in my book 😅

**Comment by abyrd** [comment]
It could be good to present more information simultaneously. We have consistently received feedback that it would be good to show multiple isochrones at once. Showing multiple percentiles at once should work just as well, since just as lower-minute isochrones are always fully inside higher minutes, higher percentile isochrones are always fully inside lower percentiles.

But with these displays I think there's a risk of information overload, so there might be a need to be able to switch them on and off, or switch between them. I would see simultaneous display of more dimensions as a good alternative or addition to interactive display, but am not convinced we'd gain anything by eliminating the interactive aspect.
