### ISSUE TITLE
Focus keyboard input fields for quick editing

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#1286]
When you take an action that will require filling out a new form, such as creating a new project or modification, much of the input comes from the keyboard and you can tab through the fields typing things in. But you have to click the first field to get started. It would be convenient if the first text field was already focused when you arrived at the form.

**Comment by trevorgerhardt** [comment]
For Modals this can be done with https://chakra-ui.com/modal#focus-on-specific-element
