### ISSUE TITLE
Add max size limits for each file upload

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#1313]
We recently had a user attempt to upload an OSM file > 400mb. We should add size limits to each file upload.

File size limits for each TBD:
- GTFS (?)
- OSM (?)
- Opportunities (?)
- Importing shapefiles to project (?)
- Aggregation Areas (?)

**Comment by trevorgerhardt** [comment]
@abyrd and @ansoncfit thought on default max sizes that we should use for each?

**Comment by trevorgerhardt** [comment]
I'd imagine 1GB for anything would be too large. What's the largest GTFS feed we've seen?

**Comment by abyrd** [comment]
In our deployment, our nginx configuration has a `client_max_body_size` of 500MB, so anything larger than that will already fail. I agree it would probably be good to validate those sizes client side before the upload to avoid confusion / disappointment when they fail. The Netherlands feed is weighing in at 250-350MB these days. Most other national scale GTFS I've encountered is smaller. 

For OSM, a Netherlands extract is over 1GB and Norway is over 700MB. However most of that is buildings, water etc. The Netherlands filtered down to just routable ways is only a bit over 100MB, which also means it's much faster to upload and process. I'd really like to encourage people to make this 10x improvement but I guess we can't force that.

Shapefiles can also be quite huge - similar observations there. Properly optimized ones are often not so bad, but we can't ask all users to spend time optimizing their file sizes. 

My sense is that the 500MB size limit in nginx is working well.

Maybe when selecting files, if size information is available and the file is seen to be large, we can display a message with a few tips on shrinking PBF files before the user uploads it.

**Comment by trevorgerhardt** [comment]
Closed in #1483
