### ISSUE TITLE
Cannot edit (fix or delete) invalid modifications

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#1367]
Some invalid values in modification JSON will cause UI errors, making it impossible to correct or delete the offending modification. For example, a remove-trips modification containing an invalid route ID will trigger a GraphQL API fetch of information about that route. Because the specified route doesn't exist, the response will contain no detail about the route, and the UI will fail when attempting to dereference an undefined object. This usually can't happen since the UI allows choosing only from lists of valid IDs fetched from the database. But because JSON can be edited manually, it's easy to accidentally create an invalid ID with a stray keystroke, quote, or comma. Any such modification must be deleted by manual intervention in the database because it causes a failed fetch of route data in the UI.

A null check could be inserted at this point, but there must be a very large number of similar failure paths. Several solutions are possible. Rather than a modal blocking further work, we could allow editing of modifications when fetch operations fail, showing some kind of warning above the raw JSON editor insisting that it needs to be fixed. 

Alternatively we could validate all IDs on the backend, returning an error with a specific message about the invalid IDs. However we probably don't want to sink much effort into doing this in the GraphQL API, it might be a good characteristic of a new simpler route-fetching API.

Process to reproduce this problem:
- Create a remove-trips modification
- Select any feed and route
- Switch to the JSON editor
- Change the routes field to `routes: ["INVALID"]`
- Save the modification
- Error message appears (the UI fails to fetch route details for ID "INVALID")

**Comment by trevorgerhardt** [comment]
With the latest modifications changes this behavior has been fixed and modifications can be deleted.
