### ISSUE TITLE
Cannot add stops to reroute segment

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#1368]
When editing the changed section of a route in a reroute modification, stops cannot be added.

**Reproducing the problem**
- Create a new reroute modification
- Select any route
- Select only a single pattern on the route for simplicity
- Select start and end stops for the rerouted segment
- The original route segment turns red, and a replacement segment is shown in blue
- Click "edit route geometry"
- Stops should be shown at the beginning and end of the rerouted segment
- Hover the mouse over the rerouted segment (cursor changes to pointing finger)
- Click to create a stop
- Nothing happens

**Expected behavior**
The final click should create a stop

**Platform:**
- OS: MacOS 10.15.7 (19H2)
- Browser: Brave ("Shields Down")
- Version: 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)

**Comment by trevorgerhardt** [comment]
Closed in #1369
