### ISSUE TITLE
Determine current version

### ISSUE THREAD

**Issue by brunetton** [conveyal/analysis-ui#1371]
Hi, 

I'm working on a dokerisation of Conveyal Analysis and to do things right I'd need to determine current version of the software.
As far as I can see the project uses [semantic versionning](https://semver.org/). 

I'm not a semver expert but as far as I understand it's supposed to generate git tags as we normally would do manually.
But the [last tag](https://github.com/conveyal/analysis-ui/releases/tag/v4.12.0) (v4.12.0) was created more than one year ago. I find it hard to imagine that no minor changes have been introduced since.

I suppose that there's no version of UI; only backend version matter.

I'm right ?

Thanks

**Comment by trevorgerhardt** [comment]
We are no longer using semantic versioning for analysis ui. Whatever makes it into `master` is the latest version.

**Comment by brunetton** [comment]
Ok thanks. 

Maybe you should remove the `semantic-release` dependency, and the "semantic-release" script from package.json
