### ISSUE TITLE
Warn on upload of large files

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#1478]
Our reverse proxy has body size limit of 500MB, which limits GTFS and OSM uploads. Even for large regions, 500MB is a lot of OSM, which is usually mostly building outlines, park benches, and other things not needed for routing, which all get loaded and slow down processing. So it probably does make sense to impose a limit.

However when you upload a larger file, it just stalls creating the bundle and doesn't show any error. We should display a message about the max file size, or even check the file size client side and refuse to upload it if it's too big, with a link to the section of the docs on filtering OSM data.

**Comment by abyrd** [comment]
This could be related to or interact with conveyal/r5#698.

**Comment by trevorgerhardt** [comment]
This is a total file upload limit ya? So if you have a 200MB GTFS file and a 400MB OSM file, that's too large?
