### ISSUE TITLE
Handle GTFS with stops that lack coordinates

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#1497]
GTFS feeds that include recently adopted pathways features may have `stops.txt` entries with `stop.lat = null` and `stop.lon = null`.

For snapping to existing stops in alignment editing (and probably other functions in the UI), any baseline stops that lack coordinates should be ignored.

**Comment by ansoncfit** [comment]
For drawing baseline stops on the map, this is already handled at https://github.com/conveyal/analysis-ui/blob/bfb6ca12cbbc40d9162046801a9a4186a56136fc/lib/components/modifications-map/gtfs-stop-gridlayer.ts#L79

**Comment by trevorgerhardt** [comment]
fixed in #1498
