### ISSUE TITLE
Baseline and default scenario names

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#1583]
In each project, we show a "baseline" scenario (which is always empty, containing no modifications). When the project is created, there is also a "default" scenario which will contain any new modifications.

This has caused some confusion. What some people call a “baseline scenario” for their case study might not be the one with no modifications. The name "default" might also be understood to mean the input data with no modifications.

We should change these to something less ambiguous, for example “no modifications” and “scenario 1".

This is apparently just a presentation layer issue (the strings "baseline" and "default" are not internally significant, just shown in the UI).

**Comment by trevorgerhardt** [comment]
Should we have two default scenarios, "No modification" and "All modifications"?

**Comment by trevorgerhardt** [comment]
A lot of use cases may fall under the "All modifications" scenario, preventing the need of adding modifications to a "Default" scenario repeatedly, whether programmatically or manually.

**Comment by ansoncfit** [comment]
Good idea on "All modifications" -- but if it's substantial effort to implement, I think the current behavior of activating a modification in the (non-baseline) scenarios that exist when it is created, in combination with the ability to copy scenarios, is good enough.

**Comment by trevorgerhardt** [comment]
Closed in #1572
