### ISSUE TITLE
Old regional analyses fail to open with keys (instead of _id) stored in grid

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#1611]
Old regional analyses, with key stored in grid (instead of ID), fail.

e.g. https://conveyal.dev/regions/7036e4c6-98bd-420e-8b5e-db97229c4307/regional/23613ead-ad21-4187-a1d0-30c2bfafb29a?cutoff=45&pointSetId=h_K_Financ_home&percentile=75

We should handle the errors and still show the analysis.

**Comment by ansoncfit** [comment]
Sorry, I deleted this from our testing sheet but forgot to close the issue.

The `.access` files for this regional analysis are not present on S3, so this failure is expected. A similar analysis (https://conveyal.dev/regions/7036e4c6-98bd-420e-8b5e-db97229c4307/regional/69cad0da-bb0b-4787-879b-ff7b39f279ee) works -- the destination selector is empty, but the key is shown in the legend, so the results are still interpretable.
