### ISSUE TITLE
"Speed painting"

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#19]
It would be really useful to be able to "paint" speeds onto trip patterns. So for example, when there's a transit line that has exclusive right of way for most of its route then runs in mixed traffic for a few blocks, it would be nice to be able to take a brush and paint that part of the line as being slower.

**Comment by mattwigway** [comment]
We can now enter it by segment but it'd be better if it was more geographic.

**Comment by trevorgerhardt** [comment]
I'm going to close this for now. We would have a massive list of issues in the category of "do this feature, but better".
