### ISSUE TITLE
Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#228]
The "Network error. Check your connection and reload the page?" dialog pops up, with detail message "Error.captureStackTrace is not a function."

![image](https://cloud.githubusercontent.com/assets/112871/22074586/ce4adb48-dde3-11e6-85fd-e333fbb72b79.png)

**Comment by abyrd** [comment]
It looks like this happens a lot in other people's projects, and there's a pattern of it working on Chrome and failing in other browsers.

**Comment by abyrd** [comment]
This Error API appears to be in V8 so is only available in Node and Chrome. Other browsers don't have the function. Some library we're using makes a call to that API without checking whether the function exists. https://www.npmjs.com/package/error-polyfill should solve the problem.

**Comment by trevorgerhardt** [comment]
Closing this as our error capture and reporting has changed drastically since this has been reported. If there is a reproducible way to get this error please let me know how and we will re-open this issue!
