### ISSUE TITLE
Analysis controls take up a lot of the page

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#237]
Currently in analysis mode the area on the left of the UI with all the controls takes up maybe 45% of the window width, even with my display scaled to a higher resolution. This width should probably be no more than 30% or so.

**Comment by abyrd** [comment]
I'm referring to the entire panel of controls on the left side of the window in scenario-editor when you go into analysis mode. If it's collapsible I don't see any control to collapse it.

**Comment by mattwigway** [comment]
Ah, you want to be able to collapse the left panel altogether and just see
the map?

**Comment by abyrd** [comment]
No, in the original ticket I just said it should not be so wide. It would probably be good to make it hidable as well, if it wasn't much trouble.
