### ISSUE TITLE
Scenario editor off top of screen

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#250]
Sometimes the UI slips off the top of my screen. This may appear after downloading a file and having the chrome downloads bar appear, but a refresh does not always solve the problem. My main concern is that it may affect my ability to do video calls, because if it slips much further off the top of my screen it will cover my camera 😛 

![image](https://cloud.githubusercontent.com/assets/566958/22344699/1a431532-e3cb-11e6-8664-0b714f98da4d.png)

**Comment by trevorgerhardt** [comment]
@mattwigway any way to reproduce this consistently? I've seen it a long time ago but not recently.

**Comment by mattwigway** [comment]
I believe entering analysis mode causes this to happen.
