### ISSUE TITLE
GIS export of scenario

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#255]
I've had a number of requests to export the scenario to GIS. I think that the output most people are looking for here is the GIS of every line in the feed including modifications. This is non-trivial but not impossible; for reroutes, we'd generate new shapes, add-trips is easy, and remove stops/trips shouldn't be too too hard except for truncation of shapes with remove-stops.

**Comment by ansoncfit** [comment]
As a first step, the ability to export .geojson of the alignments of add-trip modifications would be helpful.

**Comment by ansoncfit** [comment]
Closing until we have explicit request for export showing removed stops, segments with altered speeds, etc.
