### ISSUE TITLE
Add "zoom to" button to modification list

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#256]
Next to the :eye: button I think we want a :mag: (or crosshairs would be even better) to zoom/pan the map to show the extent of that modification.

**Comment by mattwigway** [comment]
No one can say I don't use enough emoji.

**Comment by trevorgerhardt** [comment]
Shouldn't we 🔍 the 🗺  to the modification automatically on 🐁 click?

🙈

**Comment by mattwigway** [comment]
I don't 🤔 so. It could make users 😕 , sometimes you'll have a really long 🚌 that would 🔍  the 🗺  to the whole 🌎 or at least the whole 🏙 .

**Comment by mattwigway** [comment]
also sometimes you want to zoom to a modification without selecting it.
