### ISSUE TITLE
Basemap is insufficiently labeled

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#259]
There are no labels for numbered roads (e.g. I-435), and often you have to zoom really far to get local street labels to appear. We may need separate basemaps for analysis mode (where you want to highlight the results) and editing mode (where you need to be able to see what streets your routes run on.

However, although we are missing the labels for interstates, we do have the paths of water slides in the basemap:
![image](https://cloud.githubusercontent.com/assets/566958/22376252/40c86800-e47b-11e6-898c-dc437bf29b73.png)

**Comment by trevorgerhardt** [comment]
@mattwigway we chatted about this briefly, we want to use Mapbox Streets while editing and only use Mapbox Light when in Analysis mode correct?

**Comment by mattwigway** [comment]
We should try that, I'm a little concerned Mapbox Streets will be too colorful.

**Comment by trevorgerhardt** [comment]
@ansoncfit we use a separate basemap and label layer from Mapbox so that we can manually position elements under or over the labels. Do you have access and familiarity with Mapbox enough to experiment with the labels to see what you would prefer?

**Comment by ansoncfit** [comment]
@trevorgerhardt yep.  I started looking into #584 too, but it seemed like we'd need to add one more layer in the UI.  I may ask you some questions on that.

**Comment by trevorgerhardt** [comment]
Updated to new Mapbox GL Light basemap
