### ISSUE TITLE
Alphabetize modifications

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#261]
Within each group of modifications, they should be alphabetized.

**Comment by landonreed** [comment]
As an alternative, we could use a custom sort order that at the very least brings the aggregated selections (i.e., `Jobs Total`) to the front of the list for each category.

**Comment by mattwigway** [comment]
So this issue is about grids, I'll make a new one for modifications.

**Comment by landonreed** [comment]
Right, sorry got ahead of myself.

**Comment by ansoncfit** [comment]
Modifications are sorted by creation date, which I think makes sense.  If someone wants to find a specific modification by name, they can use they search feature.
