### ISSUE TITLE
Alphabetize grids

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#266]
We should alphabetize the destination grid selection in analysis mode. @landonreed also proposes a custom alphabetizer that puts aggregate categories (Jobs total, workers total) at the top. That's country specific, but I think it would be fine to use Jobs total as the default if it exists.

**Comment by ansoncfit** [comment]
See https://github.com/conveyal/analysis-backend/issues/46

We could also re-implement the legacy Analyst feature of allowing renaming of pointset titles and attributes.

**Comment by ansoncfit** [comment]
Fixed (maybe in #528?)
