### ISSUE TITLE
Can't use report generation feature

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#267]
I get this message in the console:

![image](https://cloud.githubusercontent.com/assets/566958/22509652/fc856a0e-e85c-11e6-9581-0fdf7716f8ac.png)

**Comment by mattwigway** [comment]
This appears to be due to changes in #236, that changed the default value of `scenario.modifications` to `null` from `[]`

**Comment by trevorgerhardt** [comment]
@mattwigway looks like we just need a change to check for modifications before calling filter in the report container ([here](https://github.com/conveyal/analysis-ui/blob/dev/lib/containers/report.js#L13)). We should create a test with a completely empty store for all of the containers also.

**Comment by mattwigway** [comment]
Yep, working on that change!
