### ISSUE TITLE
analysis.conveyal.com is slow to load

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#275]
This is because we have a huge js asset to pull down from S3. We could use cloudfront to provide gzip and lower latency, but that slows down deployment somewhat. I'd consider just gzipping the files on S3 and adding the appropriate Content-Encoding metadata. We should also figure out what's in the bundle that doesn't need to be.

**Comment by trevorgerhardt** [comment]
@mattwigway how does that slow down development?

**Comment by mattwigway** [comment]
When we deploy we have to wait for an invalidation to complete.

**Comment by trevorgerhardt** [comment]
Yes, but we really shouldn't be deploying that often.

**Comment by mattwigway** [comment]
I agree in the long term, but at the moment we frequently have to deploy hotfixes to complete a project we're working on.

**Comment by trevorgerhardt** [comment]
Has it become noticeably slower recently?

**Comment by trevorgerhardt** [comment]
We should put the Analysis UI assets on production behind CloudFront at this point. Maybe not staging, but definitely production.
