### ISSUE TITLE
Incorrect display of multi-byte characters

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#281]
If I name a project using a multi-byte Unicode character (é) the character appears correctly in the text entry field, then when the project is saved the character appears correctly briefly in the main scenario editor interface, but once the spinner stops spinning (I suppose this means the project has been sent to the database and re-loaded) the é is replaced with two question mark placeholders.

Another clue: before I edited the name of the project it already included an `é` character and was displaying properly, so apparently a multi-byte character already in the database can make it all the way back to the UI. Maybe the character is being corrupted when sent to the backend or database.

**Comment by mattwigway** [comment]
I can't reproduce this locally or on the staging server. I'm wondering if it's possible that this is a font issue of some sort, although that wouldn't explain why it was working and then stopped.

**Comment by mattwigway** [comment]
@abyrd what is your locale/language set to?

**Comment by abyrd** [comment]
I'm on Chrome, using English (United States). My first impression is that it's not a font issue because the name displays correctly for a moment until the spinner spins, at which point it's replaced with the two question marks. Also, the multibyte character is clearly visible until it gets saved and re-loaded. Firefox shows exactly the same behavior. 
![image](https://cloud.githubusercontent.com/assets/112871/22915912/ace5a97e-f2b5-11e6-9f03-c32f526dff2e.png)
![image](https://cloud.githubusercontent.com/assets/112871/22915917/b5762b40-f2b5-11e6-8ded-5994111468ea.png)

I suspect this has something to do with character composition. Some component in our system is normalizing the UTF-8 to de-compose characters into (e) + (´) rather than (é) but it's not clear to me why that wouldn't display.

**Comment by abyrd** [comment]
Well, maybe it's not character composition. If I use Chinese characters 都會, they get expanded to six unknown character glyphs after I leave the page and come back: `������` The UTF-8 representation of these two characters is 6 bytes long.

**Comment by mattwigway** [comment]
This occurs for me on production but not on staging, despite those two systems being theoretically identical. $(%*&^@*. Or should I say ������?

**Comment by mattwigway** [comment]
Looks like it's not an nginx issue. If I ssh-tunnel the page I see the same thing.

**Comment by mattwigway** [comment]
I'm not sure what fixed this but it's fixed. Possibly an update to babel.
