### ISSUE TITLE
Report errors when uploading GTFS

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#283]
Upon uploading a ZIP of GTFS and OSM, the progress spinner just keeps spinning indefinitely. I see errors in the server-side logs including some uncaught exceptions, but the new bundle is visible in the UI, and I can't tell if the errors have somehow corrupted or affected the upload.

If an exception is caught on the server side, we should set the upload status to "error" with a message containing the stack trace.

**Comment by demory** [comment]
+1

I just tried creating a bundle from a GTFS file (SEPTA's) that has ZIPs within ZIPs, and the spinner just spun forever.

Granted I should have checked the GTFS first, but still, an "invalid GTFS" error message in the UI would be helpful.

**Comment by abyrd** [comment]
gtfs-lib already detects the case where the GTFS .txt files are in a subdirectory, maybe we should also detect and compensate for the case where they're double-zipped. I don't know how common that is though, I've never seen it (other than this SEPTA case you mention).

**Comment by ansoncfit** [comment]
We're slowly making progress on this:

![image](https://user-images.githubusercontent.com/2173529/44186288-90f99c80-a0e6-11e8-85c2-cd6aa0273b19.png)

We should format the error message so it looks cleaner, and maybe use `.all-copy` from `styles.css` to make it easier for users to send us these errors.

See also https://github.com/conveyal/analysis-backend/issues/15

**Comment by abyrd** [comment]
Nice, bubbling errors up to the web UI will go a long way toward helping the users and helping us diagnose problems fast.

**Comment by Nate-Wessel** [comment]
I wonder if it would be worthwhile using something like https://github.com/google/transitfeed/wiki/FeedValidator to automatically give a summary of major errors to the user. That might be easier than trying to reinvent the wheel in R5.

**Comment by Nate-Wessel** [comment]
It's worth noting that a lot of potential errors in a GTFS feed are only detected when the network gets built during the first single-point analysis. This could be a problem if someone has already started creating modifications that can't easily be transferred to a new, corrected bundle.
