### ISSUE TITLE
Make it clear that you can select multiple files when creating a bundle

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#284]
When creating a bundle, you can only supply GTFS feeds (not ZIPs of multiple feeds and OSM, as in the old UI) but you can upload more than one at a time. A few words in the UI could make that more obvious.

**Comment by ansoncfit** [comment]
"Bundles are a collection of one or more GTFS feeds." - 22fe7cab4c9a845f678ea3a5c165ba66e6eb4c2f
