### ISSUE TITLE
Animate travel time cutoff

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#289]
It's pretty impressive to see / show off the isochrones grow outward from the origin point. It would be nice to have a button that automatically cycles the travel time slider from 0 to 120 in a loop.

**Comment by mattwigway** [comment]
We'll need to make the rendering a lot faster for this to work.

**Comment by abyrd** [comment]
@mattwigway you mean with vector or raster isochrones? At least with the raster isochrones, once they are calculated they already render smoothly as the slider is moved.

**Comment by mattwigway** [comment]
With the raster isochrones, they're still not quite smooth when the slider is dragged.

**Comment by trevorgerhardt** [comment]
I'd rather not do this unless 100% necessary. Animation is nice, but not necessary. A super fast UI without animation may be crippled by adding it in.
