### ISSUE TITLE
UI to show workers

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#290]
The broker now has an endpoint that shows a lot of information about the whole worker pool (try `$ watch -n5 "curl -s 10.0.0.120:9001/workers | python -mjson.tool"` on `analysis.conveyal.com`). It would be great to have a simple page showing all active workers and their CPU and memory load.

Some specific items that could be displayed:

- A stacked bar graph (single bar) of memory consumption, with memoryFree < memoryTotal < memoryMax
- CPU load bar, showing loadAverage and processor count as text, and bar proportionate to loadAverage/processors
- Active network IDs and scenario IDs

**Comment by ansoncfit** [comment]
Closed in https://github.com/conveyal/analysis-ui/pull/674
