### ISSUE TITLE
Cannot contact backend

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#297]
The frontend sometimes locks up and cannot contact the backend. I think this is due to the change I made from Unirest to Apache HTTPComponents last night, which solved some issue (I think). It looks like HTTPComponents only allows two simultaneous connections per route, and has no timeout. So if two requests to the broker don't come back for whatever reason (or maybe if there's nowhere to write output to?), no more requests can be made, and it's all over now, baby blue.

Sure enough, `jcmd <pid> Thread.print` on the frontend indicates that two threads are stuck in `socketRead0()` (er, actually three).

**Comment by landonreed** [comment]
@mattwigway, I'm not entirely sure, but this could have been the same issue I reported a couple of weeks ago when I tried to demo for ARC.  The front end seemed frozen (the loading spinner just kept on spinning indefinitely).

**Comment by mattwigway** [comment]
Hmm, that's possible, although if that's the case it's not what I suspect it is.

**Comment by landonreed** [comment]
Right, just wanted to warn that this could be something else if the frozen behavior was similar to my experience.

**Comment by mattwigway** [comment]
Okay, I can now reliably reproduce this by making a request with a zero-width time range.

**Comment by mattwigway** [comment]
I think it's causing the worker to block, and then any more requests to that worker cause the frontend to lock due to the connections being held open.

**Comment by mattwigway** [comment]
So I think there are two problems: the workers are locking with a zero-width time range, and the frontend can't handle that.

**Comment by mattwigway** [comment]
I think that adding timeouts to the Apache HTTP client instantiation will solve this issue. I did that but for my demo today just reverted to the Unirest version of the frontend.
