### ISSUE TITLE
Cannot delete all contents of a number box

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#304]
If you delete all the way to the beginning of a number input (e.g. the speed in a timetable) it will reset to 1, not blank. I think we need to not call onChange when the input is cleared, and keep the value in state.

**Comment by trevorgerhardt** [comment]
@mattwigway I'll start a PR with the speed in a timetable fixed, but this should probably be done on a case by case basis. Let me know which other ones have a problem!

**Comment by mattwigway** [comment]
@trevorgerhardt what's the reasoning for not having this be default behavior? It seems like not being able to delete all the contents of a number box is never desirable.

**Comment by trevorgerhardt** [comment]
This input is unique as it's value is not directly stores and is calculated by other values (it's an average of the overall speed). 

I can see how having a null/empty value would be desireable.

**Comment by mattwigway** [comment]
I don't think we have any boxes now that can be set to null; what if we just added 'nullable' option to the number input and defaulted to not passing back empty values.

**Comment by trevorgerhardt** [comment]
Number inputs have changed drastically since this issue was opened. Closing.
