### ISSUE TITLE
When returning to a comparison, comparison checkbox will be backwards

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#317]
If you enter analysis mode and do a comparison, then go back to scenario editing mode, then return to analysis mode, the comparison will still be active and the selectors to choose a comparison scenario will still show, but the checkbox will function backwards (i.e. it shows no comparison is active when it is and vice-versa).

**Comment by trevorgerhardt** [comment]
fixed in the styling branch
