### ISSUE TITLE
sh: 1: yarn: not found

### ISSUE THREAD

**Issue by heshammaz** [conveyal/analysis-ui#321]
sh: 1: yarn: not found

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @conveyal/analysis-ui@0.0.0-semantic.release prestart: `yarn`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @conveyal/analysis-ui@0.0.0-semantic.release prestart script 'yarn'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @conveyal/analysis-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yarn
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @conveyal/analysis-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @conveyal/analysis-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/admin1/git/analysis-ui/npm-debug.log

**Comment by trevorgerhardt** [comment]
Install  [yarn](https://yarnpkg.com/en/) before you can use `npm start`

**Comment by heshammaz** [comment]
I'll try it now, 
thank you for the quick response

Hesham
