### ISSUE TITLE
Error: Unable to parse.

### ISSUE THREAD

**Issue by heshammaz** [conveyal/analysis-ui#324]
admin1@admin1-VirtualBox:~/analyst_project/analysis-ui$ npm start

> @conveyal/analysis-ui@0.0.0-semantic.release prestart /home/admin1/analyst_project/analysis-ui
> yarn

yarn install v0.21.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.97s.

> @conveyal/analysis-ui@0.0.0-semantic.release start /home/admin1/analyst_project/analysis-ui
> npm run build -- --serve --proxy http://localhost:7070/api

> @conveyal/analysis-ui@0.0.0-semantic.release build /home/admin1/analyst_project/analysis-ui
> mastarm build lib/index.js:assets/index.js lib/styles.css:assets/index.css "--serve" "--proxy" "http://localhost:7070/api"

/home/admin1/analyst_project/analysis-ui/node_modules/yamljs/lib/Parser.js:268
        throw new ParseException('Unable to parse.', this.getRealCurrentLineNb() + 1, this.currentLine);
        ^
Error: Unable to parse.

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--" "--serve" "--proxy" "http://localhost:7070/api"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @conveyal/analysis-ui@0.0.0-semantic.release build: `mastarm build lib/index.js:assets/index.js lib/styles.css:assets/index.css "--serve" "--proxy" "http://localhost:7070/api"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @conveyal/analysis-ui@0.0.0-semantic.release build script 'mastarm build lib/index.js:assets/index.js lib/styles.css:assets/index.css "--serve" "--proxy" "http://localhost:7070/api"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @conveyal/analysis-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mastarm build lib/index.js:assets/index.js lib/styles.css:assets/index.css "--serve" "--proxy" "http://localhost:7070/api"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @conveyal/analysis-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @conveyal/analysis-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/admin1/analyst_project/analysis-ui/npm-debug.log

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @conveyal/analysis-ui@0.0.0-semantic.release start: `npm run build -- --serve --proxy http://localhost:7070/api`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @conveyal/analysis-ui@0.0.0-semantic.release start script 'npm run build -- --serve --proxy http://localhost:7070/api'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @conveyal/analysis-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build -- --serve --proxy http://localhost:7070/api
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @conveyal/analysis-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @conveyal/analysis-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/admin1/analyst_project/analysis-ui/npm-debug.log

**Comment by heshammaz** [comment]
well from this point I can assume that everything's fine, But the first step which I need to run my Analyst Server. 

I am having a bit of problem there.
According to the below error which encountered while running ( mvn install ) the in the analysis environment I would say that the maven is missing the snapshot. 

admin1@admin1-VirtualBox:~/analyst_project/analyst$ mvn install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.conveyal:analyst:jar:0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 12, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building analyst 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.sparkjava:spark-core:jar:2.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.slf4j:slf4j-api:jar:1.7.12 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for ch.qos.logback:logback-classic:jar:1.1.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.mongodb:mongo-java-driver:jar:3.2.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.mongojack:mongojack:jar:2.5.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.fasterxml.jackson.core:jackson-core:jar:2.6.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.fasterxml.jackson.core:jackson-databind:jar:2.6.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
Downloading: https://maven.conveyal.com/com/conveyal/r5/2.0.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://maven.conveyal.com/com/conveyal/r5/2.0.0-SNAPSHOT/maven-metadata.xml (767 B at 0.5 KB/sec)
[WARNING] The POM for com.vividsolutions:jts:jar:1.13 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for de.grundid.opendatalab:geojson-jackson:jar:1.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for net.sf.trove4j:trove4j:jar:3.0.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for net.sourceforge.javacsv:javacsv:jar:2.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
.
.
.
.

Any susgation ?

**Comment by mattwigway** [comment]
This was due to a misconfiguration in our Maven repository which is now fixed. You may need to clear ~/.m2/repository in order for it to build correctly.

**Comment by heshammaz** [comment]
Can you be kind enough and replay to this post,

https://github.com/conveyal/analyst/issues/20
[https://avatars0.githubusercontent.com/u/24889220?v=3&s=400]<https://github.com/conveyal/analyst/issues/20>

Can't find the application.conf · Issue #20 · conveyal/analyst<https://github.com/conveyal/analyst/issues/20>
github.com
Can anyone please highlight a way to get application.conf ???? Thanks in advance Hesham



I am a beginner and this error driving me crazy.....


Best
Hesham



________________________________
