### ISSUE TITLE
Must hard-reload page to see grids

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#339]
I find that I frequently get stuck unable to take any actions in analysis mode because there are no grids available in the drop down list, and I get JS console errors caused by undefined variables.

When I reload the page, the grid list is populated and things begin working as expected.

**Comment by mattwigway** [comment]
Is this happening specifically on new projects? If so, it will be fixed by #323 .

**Comment by abyrd** [comment]
It was on a new project, but after I'd seen the backend upload all the extracted census data. Ah, but I suppose maybe it had to re-download that census data.

**Comment by mattwigway** [comment]
Yeah, currently the frontend dies not automatically check to see if census
data has been uploaded.
