### ISSUE TITLE
Export single-point analysis results for use in GIS

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#344]
There are several categories of data to be exported: 
1. raw travel time grids
2. isochrones
3. histograms of opportunity counts

We will soon be doing raster interpolation on the travel time grids for display, but I don't think we should ever export our own interpolated images. If someone knows how to load a raster into GIS, they will also figure out how to interpolate it in GIS, and take responsibility for the methods used. If they don't know how to load a raster they may want to use pre-prepared vector isochrones, and I'm thinking we should just run the travel times through browsochrones' marching squares to get those vector shapes, which we can export at GeoJSON or something.

**Comment by mattwigway** [comment]
I agree with all this, and in fact was planning to write the code to do this this week, at least for the vector isochrones. I'm thinking though that the vector isochrones look blocky compared to the interpolated raster isochrones, so I'd be in favor of interpolating a grid before making the vector isochrones. Completely agreed though that we should never export "raw" interpolated travel time grids.

**Comment by trevorgerhardt** [comment]
As a first step we will add the ability to export isochrones as GeoJSON

**Comment by ansoncfit** [comment]
As a second step, we could add the ability to export as .shp (maybe with https://github.com/mapbox/shp-write)

**Comment by abyrd** [comment]
I don't know if we want to add shapefile export - it's really a terrible format and QGIS can read GeoJSON among other things. I'm not sure it's worth more dependencies.

**Comment by ansoncfit** [comment]
👍 

For clients who need .shp and whose IT departments won't let them install QGIS, I'll add a note to the user manual suggesting http://mapshaper.org/

To close this out, we'd want a .csv download for the histogram data?

**Comment by abyrd** [comment]
Ideally we want all raw data to be exportable, as many of our clients / users want to do their own post-processing. We don't want to hold people back due to our assumptions about how raw data should be displayed and used. 

The raw results for a single point analysis are travel times to each grid cell, which can be downloaded as a raster, but become more useful if the user can also download the opportunity densities as a raster. We also have N different travel times, typically 5. So the ideal output would be a six-plane raster with the 5 layers of travel time and a density of opportunities on the sixth.

We've also already performed the cumulative accessibility computations in the UI, so we'd want to be able to export that as CSV. Five rows, one for each percentile of travel time, with columns being cumulative opportunity counts for each minute of travel.

Looking back at the original ticket @ansoncfit, I don't even know what I meant by "histograms of opportunity counts".

**Comment by ansoncfit** [comment]
Would we want that sixth band in the raster with opportunity data?

I might prefer to have a separate option to download opportunity grids (https://github.com/conveyal/analysis-ui/issues/511) to avoid having them clutter the travel time rasters.

**Comment by abyrd** [comment]
True, we shouldn't assume which one they want to export. The main advantage of putting them in the same raster file is that it might make some GIS operations faster - I'm not sure if QGIS / GDAL will figure out that the time and oppurtunity rasters are in exactly the same projection and inter-cell pitch and apply the possible optimizations.

**Comment by ansoncfit** [comment]
We have implemented .geotiff exports of opportunity grids and travel time surfaces.  Users can make their own histograms offline, using e.g. https://cran.r-project.org/web/packages/raster/index.html

Closing for now.
