### ISSUE TITLE
Spectrogram selector does not work

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#355]
When doing a comparison, the buttons to select which scenario is displayed in the spectrogram are shown but do nothing. No errors are present in the console.

**Comment by mattwigway** [comment]
It looks like the label update broke radio buttons.

**Comment by trevorgerhardt** [comment]
Can we check this with a test?

**Comment by mattwigway** [comment]
I'm not sure how we'd test it, the problem is that onChange events are not firing.

**Comment by trevorgerhardt** [comment]
We should be able to simulate a click event that *should* fire the onChange event.
