### ISSUE TITLE
No user feedback when loading comparison grids

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#366]
When you compare two regional analyses, it can take quite a while for them to load. There is no user feedback during this operation.

**Comment by Nate-Wessel** [comment]
Does this still take a long time? I haven't experienced any issue and the downloadable TIFF files at least seem quite lightweight.

**Comment by ansoncfit** [comment]
Shouldn't be an issue since removing the bootstrap approach.
