### ISSUE TITLE
Weighted Average Accessibility

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#376]
- [ ] Upload and name a Shapefile/GeoJSON of Polygons
- [ ] Select a polygon from a list "Show Weighted Average Accessibility for"
- [ ] Display the borders of the polygons along with the WAA inside the polygons

**Comment by ansoncfit** [comment]
@abyrd and I discussed this further today, in relation to an analysis that needs to be complete for Montevideo next week.

Aggregation polygons should not just be boundaries; users should also be able to select an attribute/shapefile column as the origin weighting class (e.g. population, low-income population, etc.).  Depending on how close these features are to being ready, and how common a use-case this will be, we may also want to try offline workflows (e.g. in GIS) that can use downloaded regional analysis result grids.

Additionally, we've had a request to report a summary value (e.g. median) on top of the histogram of the distribution of accessibility among the selected origin class...

**Comment by ansoncfit** [comment]
The last part (summary values) are already taken care of, with an appropriate ⚠️ for the average.

**Comment by ansoncfit** [comment]
Need to add clarification in docs that for now, fields to be used for weighting should be uploaded as opportunity datasets (aggregation area upload is only only used for an envelope, not attributes)

**Comment by abyrd** [comment]
@ansoncfit were you able to determine how it works now? I don't see how this could possibly be implemented without a step where you choose the weighting grid. Otherwise what would determine how many times each accessibility value is counted in the final distribution?

**Comment by ansoncfit** [comment]
Yes, the weighting requires choosing a grid, @abyrd. It took me a bit to remember that those grids are uploaded in the same place as opportunities, not pulled in from the aggregation area shape. I'll keep this open until I update the documentation with that clarification.

**Comment by abyrd** [comment]
Right, the weighting data can't be included in the aggregation boundary shapes, because we need one population count per grid cell and there can be many grid cells inside an aggregation boundary.
