### ISSUE TITLE
Show summary of jobs and travel time difference on map mouse hover

### ISSUE THREAD

**Issue by landonreed** [conveyal/analysis-ui#380]

**Comment by mattwigway** [comment]
I think this should be addressed by #436, no?

**Comment by ansoncfit** [comment]
@landonreed can you confirm this should be closed, or add some more detail on what "summary of jobs" would be?  The count of opportunities in a given grid cell?

**Comment by landonreed** [comment]
Yea, I think this can be closed based on some of the work I saw demoed by you and Matt.
