### ISSUE TITLE
Automatic duplication of timetables or referencing existing timetables

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#390]
When making a new line, you might want the same frequencies and inter-stop times at e.g. 5-6 AM and 11pm. Currently you need to re-type everything repeatedly.

**Comment by mattwigway** [comment]
Duplicate of #264.

**Comment by abyrd** [comment]
Sorry about any duplicates, I was just firing these off during a conversion to make sure they got recorded.
