### ISSUE TITLE
Clarify access/egress limits as being per-leg, and prevent limits from exceeding hardwired R5 limits

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#396]
Networks have hard-wired upper limits on per-leg times for different modes. We need to make these upper limits visible in the UI. It should also be clarified in the UI that these limits apply to each leg.

Old comment:
Research in Marseille shows almost no one walks more than 600m, so accessibility figures in peri-urban areas are exaggerated.

**Comment by mattwigway** [comment]
I assume this is for the initial walk to transit?

**Comment by abyrd** [comment]
I would say initial and final walk both. The core idea is to respect the maximum tolerance for walking observed in the field.

**Comment by mattwigway** [comment]
Right, I just meant not for walk-only searches.

**Comment by abyrd** [comment]
On the back end R5 is hard-wired to a 2km distance limit for access to transit. We need to pull this walk limit out of the request, and provide it with a selector or slider in the UI.

**Comment by ansoncfit** [comment]
The UI now has fields for maxWalkTime and maxBikeTime.  We should add notes clarifying that these limits are per-leg, and set reasonable maxima for them to avoid crashing workers.

**Comment by ansoncfit** [comment]
The hardwired limit (`TransitLayer.DISTANCE_TABLE_SIZE_METERS`) is used when constructing `stopToVertexDistanceTable`s at network build.  Unless we want to put effort into coding ways for these tables to be rebuilt, we should make sure it is a generous upper bound and allow users to lower distance limits (but not raise them) in requests.

We could disallow users from setting combinations of speed and maxTime in the UI that would make the hard-wired limits in R5 binding (or at least show a warning if they attempt to do so).

**Comment by ansoncfit** [comment]
In R5 v4.6.0, 
- `WALK_DISTANCE_LIMIT_METERS = 2000`
- `BICYCLE_DISTANCE_LINKING_LIMIT_METERS = 5000`
- `CAR_TIME_LINKING_LIMIT_SECONDS * MAX_CAR_SPEED_METERS_PER_SECOND` = 79200

In the UI, 
- Walk speed (in m/s) * max walk time (in minutes) * 60 should be constrained to be less than 2000, with a warning when users try to exceed it: "Per-leg walk limit cannot exceed 2 km."
- Bike speed (in m/s) * max bike time (in minutes) * 60 should be constrained to be less than 5000, with a warning when users try to exceed it: "Per-leg bike limit cannot exceed 5 km."
- If we add car speed/time limits, they should be constrained similarly.

**Comment by ansoncfit** [comment]
Amendment: because times for the initial access leg come from a street router, not pre-computed tables, this leg can exceed the hard-coded R5 limits.

So we could just note in the UI or docs that the "advanced settings" will be applied to the initial access leg, but lower limits may apply to transfer and egress legs (note a lower car limit may be implemented per https://github.com/conveyal/r5/issues/535)
