### ISSUE TITLE
Something is rotten with the regional analysis comparison legend

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#397]
![image](https://cloud.githubusercontent.com/assets/566958/26476916/b441af1e-4176-11e7-8809-86851356f8a9.png)

This is comparing biking to transit to walking to transit, so it should be more or less uniformly positive, and it is. However, the lowest category is not empty, but also shows its lower bound as not being negative - ??

**Comment by Nate-Wessel** [comment]
There seem to have been enough changes to the legends that this is no longer relevant and/or was resolved a while ago but not closed.
