### ISSUE TITLE
Park and Ride mode option

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#398]
AGAM and probably other clients are interested in park-and-ride analysis. On the front end we just need a button to signal this mode to the backend in requests. @abyrd will take care of backend changes.

We need this functionality working in time for @chourmo at AGAM to perform analysis in mid-June.

**Comment by ansoncfit** [comment]
d368654a6b40e6b5249b6f2f6a7c5b08d0d24641 closes, and should be pushed to production soon.
