### ISSUE TITLE
Copying scenario (using Import Modifications From) button does not copy phase from timetable correctly

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#402]
It seems to still work in analysis mode, but the UI does not display a phase from timetable.

**Comment by trevorgerhardt** [comment]
Due to changing modification ids this is a little bit trickier than copying one modification at a time.

**Comment by mattwigway** [comment]
Ah, I didn't realize that the modification IDs were stored in the phase from timetable. Since entry ids are scenario-unique but not globally unique, we could copy all the modifications and preserve their entry IDs, then build a map from entry ID to modification ID, and then update all the phaseFromTimetable information with the new modification IDs.
