### ISSUE TITLE
UI regional analysis progress bar lags behind the broker

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#405]
The broker reports 3144 origins complete, while the UI progress bar reports 2126. Is this expected?

Even more strange, there are two jobs on the broker (using the same network). Both of them have some number of completed tasks (5264 and 2769). But in the UI, only one of the jobs shows any completion and the other is at 0%.

**Comment by abyrd** [comment]
It appears that this might be due to the server running out of disk space, so the result assembler is failing.

**Comment by abyrd** [comment]
It appears that the UI is reporting the state of the grid assemblers on the backend, never looking directly at the broker jobs. This is also why the UI progress often lags behind the broker's reported progress on a given job: the UI is reporting how many tasks the grid assembler has pulled off the SQS queue and slotted into place, not how many tasks have been reported completed by the workers.

**Comment by abyrd** [comment]
It appears that the UI is reporting the state of the grid assemblers on the backend, never looking directly at the broker jobs. This is also why the UI progress often lags behind the broker's reported progress on a given job: the UI is reporting how many tasks the grid assembler has pulled off the SQS queue and slotted into place, not how many tasks have been reported completed by the workers.

**Comment by abyrd** [comment]
See also conveyal/analysis-backend#79 - I bet there's an AWS IOPS cap effect here too.

**Comment by ansoncfit** [comment]
This has been resolved by the new integrated broker setup.
