### ISSUE TITLE
Limit analysis time window and number of random timetables

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#412]
We had a line in our stock contract about time window and number of random timetables. Rather than bury this in a contract we should just impose reasonable limits in the UI.

**Comment by ansoncfit** [comment]
Time window:
- Not longer than 8 hours?
- Start time must be before end time.
- End time plus max trip duration must be before midnight (until https://github.com/conveyal/r5/issues/286 addressed)?

Max number of random timetables: 1500?

**Comment by abyrd** [comment]
In order to set a max number of random timetables, we need to establish what a good number is for final analyses. Conveyal has done research on how to do this analytically but a simple empirical "sensitivity test" should be sufficient to get started. Basically we just re-run an analysis (on a network with a mix of frequency-based routes at different frequencies in different areas) then bump the number of schedules up until results stabilize to within acceptable limits. We should be able to get a sense of how results converge in areas with different service frequencies and with different levels of connectivity to dense areas.

**Comment by ansoncfit** [comment]
Bumping the second bullet here, which would have prevented errors in a recent training. ToTime should never be before FromTime.

**Comment by ansoncfit** [comment]
We should prioritize this, as users perceive the system as unresponsive when they request too many simulated schedules (2000 in a recent example).

If it takes longer than the timeout limit (45 seconds?) for a worker to process results, the broker gives up (logging `Timeout waiting for response from worker. Perhaps an old version of R5 has blocked while preparing a network.`) and signals the UI to try again.  Requests pile up on the worker and it eventually needs to be terminated.

**Comment by ansoncfit** [comment]
Closed in #1184
