### ISSUE TITLE
Bad URLs don't lead to a 404 page

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#437]
When logged in, if you manually specify a URL that doesn't correspond to anything in our app you get a blank page. You're already within the app at this point so nginx is not going to supply the 404 page, our app needs to serve a "bad URL" page.  Or maybe just return to the main page of the app.

**Comment by trevorgerhardt** [comment]
Added in https://github.com/conveyal/analysis-ui/pull/427/commits/4460db5f68746054e511d2d2ad0fe69c02e53479
