### ISSUE TITLE
Cannot create new project

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#440]
On scenario-editor-staging, when I enter the dialog to create a new project, I see the message that "There is a more recent version of the analysis backend available" but no version is selected, and no versions are visible in the list.

![image](https://user-images.githubusercontent.com/112871/27676619-3eb81d06-5ce1-11e7-820b-48eda382b54b.png)

**Comment by trevorgerhardt** [comment]
This should be fixed in f8bcb270604c78833d04993df7d646bb542e11d7
