### ISSUE TITLE
Single analysis settings object

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#443]
@trevorgerhardt mentioned a while back that he'd like to see a single analysis settings object for analysis-ui, rather than having objects corresponding to R5 ProfileRequests as well as ancillary information.

This will be easier once conveyal/r5#298 is merged. See also references to this issue within the analysis-ui codebase (`ag #443`)

**Comment by trevorgerhardt** [comment]
We no longer have this goal.
