### ISSUE TITLE
Preview CloudWatch logs in "debug" view

### ISSUE THREAD

**Issue by landonreed** [conveyal/analysis-ui#445]
@abyrd and I discussed that it might be helpful to users to show CloudWatch logs for a job (or even just during normal operation), possibly as part of a "debug" view.  I'm not sure if this should be visible for all users or just admins.

**Comment by abyrd** [comment]
Actually the backend has access to those workers, so we could conceivably stream the logs back over http to the admin console. That would be amazing.

**Comment by trevorgerhardt** [comment]
Out of date
