### ISSUE TITLE
Remove trips for multiple trips

### ISSUE THREAD

**Issue by chourmo** [conveyal/analysis-ui#457]
When editing a large network, it would simplify variant sets if it was possible to delete several trips in the same "remove trips"

**Comment by ansoncfit** [comment]
To clarify, multiple patterns can be selected for a given route.

But multiple routes cannot be selected in one remove trip modifications.  It would be great if multiple routes, or even all routes in a given feed, could be selected.

**Comment by ansoncfit** [comment]
This was also requested by PUC users a couple months ago.
