### ISSUE TITLE
Allow following rails as well as streets in geometry editor

### ISSUE THREAD

**Issue by chourmo** [conveyal/analysis-ui#459]
Just as the "follow streets"

**Comment by ansoncfit** [comment]
I don't think we could make this work well given Mapzen's current [costing models](https://mapzen.com/documentation/mobility/turn-by-turn/api-reference/#costing-models).  We could revisit later.

**Comment by Nate-Wessel** [comment]
This is possible with OSRM, though that may be too much to set up and keep updated.

**Comment by trevorgerhardt** [comment]
We're quite far away from this being possible with our current set up. Going to close for now.
