### ISSUE TITLE
Node selection in remove stops

### ISSUE THREAD

**Issue by chourmo** [conveyal/analysis-ui#461]
How do i select nodes to remove ?

**Comment by ansoncfit** [comment]
The existing leaflet draw icon used for selecting stops is not intuitive.  This needs revision.  At the very least, it should be moved to the lower left of the leaflet pane, and an explanatory tooltip should be added.

![image](https://user-images.githubusercontent.com/2173529/30452751-bd9788e0-9964-11e7-9c13-504b9fe2d5c4.png)

**Comment by ansoncfit** [comment]
This issue generated another set of support requests last week.

**Comment by trevorgerhardt** [comment]
For the time being let's just add text underneath the "Selection" heading that more clearly guides the user when they click "Select". The drawing tool we currently use is not the easiest to customize.
