### ISSUE TITLE
Maps are sideways in report

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#470]
In reports, all the maps that are supposed to have north at the top are turned sideways.

![image](https://user-images.githubusercontent.com/566958/28464876-de162a90-6df4-11e7-847c-993809c5c8db.png)

**Comment by ansoncfit** [comment]
This is still happening, though it doesn't seem consistent.

**Comment by trevorgerhardt** [comment]
Is there a specific occurrence where I can reproduce this or more details about the browser/OS? I am unable to reproduce this locally.

**Comment by ansoncfit** [comment]
@demory (Chrome, Mac) and I (Chrome, Windows) just saw this at https://analysis.conveyal.com/reports/1d284e5b-e6e8-454a-8f78-d1bc37dfeecd/projects/5ad4df5c896fd072a1c7f437/variants/0 (access group = trimet)

His theory is that it has to do with the add trip modification having incorrect leaflet styling.

**Comment by ansoncfit** [comment]
The rotated labels are a bit jarring.

Always keeping north up could lead NS and EW routes to be shown at different scales, which could be a bit confusing.  We could make the maps square to mitigate this issue.

The printable reports aren't being used heavily at the moment, so whatever works as a quick fix is fine with me.

**Comment by trevorgerhardt** [comment]
Yea, I get that issue. I've never looked at reports produced by anyone else and am open to rotation if we change to `mapbox-gl` (which allows for that). For now I'll just disable it so it works.

**Comment by abyrd** [comment]
I don't think we need to save space on the images by rotating them. The changes could take up a whole page and it shouldn't hurt anything. At least I hope no one is printing these out...
