### ISSUE TITLE
Top of screen out of screen bounds

### ISSUE THREAD

**Issue by chourmo** [conveyal/analysis-ui#477]
The top of the screen is out the the screen bounds and I cannot get it back. A row of white is at the bottom of the screen.

I will try to find the reasons of this bus.

Reload from analysis.conveyal.com restores of normal screen.

**Comment by ansoncfit** [comment]
Not sure if it's the same issue, but this happened on production when a regional analysis was running:

![image](https://user-images.githubusercontent.com/2173529/30830479-294c1302-a212-11e7-8802-6ed94fa3120f.png)

**Comment by trevorgerhardt** [comment]
@ansoncfit I've thought I've fixed this bug a few times...latest "fix" is on staging so unless it can be reproduced there I think there is a good chance I got it this time 👌

**Comment by ansoncfit** [comment]
Sounds good.  I'll close for now, and re-open if I see this again on the latest version.
