### ISSUE TITLE
Key modifiers for trip drawing

### ISSUE THREAD

**Issue by chourmo** [conveyal/analysis-ui#480]
When drawing or rerouting a trip, I would greatly appreciate keyboard modifier (shift, alt...) to

- create a stop or a control point
- switch follow route mode

**Comment by landonreed** [comment]
Here are some references in datatools-ui that might be helpful:

- [Help modal documenting keyboard shortcuts](https://github.com/catalogueglobal/datatools-ui/blob/trip-validation-improvements/lib/editor/components/timetable/TimetableHelpModal.js)
- [Gigantic key press handling function](https://github.com/catalogueglobal/datatools-ui/blob/trip-validation-improvements/lib/editor/components/timetable/TimetableGrid.js#L93)
