### ISSUE TITLE
Cannot be logged in as multiple users in different tabs

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#481]
It appears that you can't log in to analysis-ui as two different users in two different tabs of the same browser. @trevorgerhardt can you confirm that this is the case?

**Comment by trevorgerhardt** [comment]
Confirmed. And it is intended behavior. That is not usually possible in any all but the most popular of web applications (Gmail). Is there a reason for needing/expecting this?

**Comment by abyrd** [comment]
Not really, I was just comparing behavior across two different projects, so it's useful for debugging. I'll close the ticket if this is expected.
