### ISSUE TITLE
Cant specify feed ID when uploading feeds

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#485]
When editing a scenario, if there are multiple feeds one needs to select a feed from a dropdown. These are just UUIDs unless the feed contains a feed_info.txt with a feed_id. In NYC with 11 feeds this makes it a pain to find the one you want.

**Comment by Nate-Wessel** [comment]
What is a `feed_id`? This doesn't seem to be part of the GTFS spec.
