### ISSUE TITLE
Mode selector

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#489]
We need to be able to select transit modes (at least activate / deactivate rail, bus).

**Comment by ansoncfit** [comment]
We should talk this through before advancing.  In legacy Analyst, users could have different mode settings for the main and comparison isochrone layers.

A recent feature request was to be able to see walk, bike, and transit access sheds for a single point all overlaid.  Could we move toward allowing users to add an arbitrary number of superimposed analyses?

**Comment by trevorgerhardt** [comment]
@ansoncfit would we want all settings to be changeable for comparison? "Compare weekday service to weekend service" etc.

**Comment by ansoncfit** [comment]
Suggestion on default selectors for transit mode: just toggle-able 🚌  and 🚈, but with an adjacent flask that replaces them with a multi-select drop-down of all modes enumerated in R5: https://github.com/conveyal/r5/blob/v2.4.1/src/main/java/com/conveyal/r5/api/util/TransitModes.java
