### ISSUE TITLE
Upload shapefile button kind of hard to find

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#491]
It took me a while to realize it's the globe icon at the top of the scenario, which situates it as a kind of global operation rather than something that adds individual modifications to the scenario. It's not absurd, but just feels a bit counterintuitive.

It also has an obscure icon. Personally I hesitate to use any non-obvious icons. Considering how rarely many people will use this, and how unlikely they are to make a permanent association between a picture of a globe and uploading a shapefile of transit lines, I think it makes more sense to have a button that says "upload route alignment shapefile".

**Comment by ansoncfit** [comment]
We could use fa-upload to upload a shapefile of a scenario, and fa-download to go to the dialog for downloading a variant .json (and maybe eventually a variant .shp, as suggested in #255)
