### ISSUE TITLE
Update Documentation about multi-select

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#492]
When you upload a shapefile you can now multi-select the component files (SHP DBF SHX etc.) but I don't see this explained anywhere in the docs at http://scenario-editor.readthedocs.io/en/latest/prepare-inputs/ 

Several people have been confused by this, and by the fact that (like too many other things) it fails completely silently with no messages at all.

**Comment by ansoncfit** [comment]
Multi-select is explained on a different page in the docs -- http://scenario-editor.readthedocs.io/en/latest/analysis/upload-opportunity-data/

But this should still be made clear in the interface (e.g. a help icon w/ tooltip).

**Comment by ansoncfit** [comment]
The combination of https://github.com/conveyal/analysis-backend/commit/58147becbbf13c4fd5d6f91b639a34e43a1ef609 and https://github.com/conveyal/analysis-ui/commit/ba67b7d3da342954f281822eed8c55203efdb963 should resolve this issue.

**Comment by abyrd** [comment]
There are additional issues with multi-select, one of which I ran into yesterday: it's impossible to select two GTFS feeds in two different folders. This could be resolved by allowing feed-by-feed management of a GTFS "pool" within a project or organization though, so you could do multiple uploads and combine them into one scenario.
