### ISSUE TITLE
Edit bundle screen has error

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#500]
After uploading two files to create a bundle, I click again on the bundle icon, then on the new bundle name in the drop-down.  The following error occurs.

![image](https://user-images.githubusercontent.com/2173529/30391822-cff7013c-9888-11e7-92a4-f5dc3b34ec0f.png)

This happens even after a refresh.

Not critical now, as the only functionality on this page is renaming the bundle and feed aliases.

**Comment by trevorgerhardt** [comment]
This issue will be attended to here: conveyal/analysis-backend#56
