### ISSUE TITLE
Stops are created automatically, even though "Create stops automatically" is unchecked

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#502]
This happens when clicking on edit route geometry for the first time:

![image](https://user-images.githubusercontent.com/2173529/30393304-9ddc2eac-988d-11e7-99a5-9f7485d8a355.png)

Checking and unchecking the box removes the extra stops:

![image](https://user-images.githubusercontent.com/2173529/30393348-c35d8c70-988d-11e7-9861-b35e8b4bb310.png)

Could lead first-time users of the scenario editing tools astray.

**Comment by ansoncfit** [comment]
This happens on staging and production.  Related to #249?

**Comment by trevorgerhardt** [comment]
Thought I fixed this already 🤔
