### ISSUE TITLE
Allow management of opportunity datasets

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#510]
Multiple users have requested better control/management of opportunity data.  I imagine the Opportunities Dataset panel looking like:

-Pointset/shapefile 1 [rename | use as sub-area | remove from list of sub-areas]
--                  [use all as grids | remove all from list of grids]
--Attribute 1 [rename | use as grid | remove from list of grids]
--Attribute 2 [rename | use as grid | remove from list of grids]

-Pointset/shapefile 2 [use as sub-area | remove from list of sub-areas]
--                  [use all as grids | remove all from list of grids]
--Attribute 1 [rename | use as grid | remove from list of grids]

-LODES (if available)
--                  [use all as grids | remove all from list of grids]
--Attribute 1 [rename | use as grid | remove from list of grids]
--Attribute 2 [rename | use as grid | remove from list of grids]
etc.

This would help avoid dropdowns that are bloated and hard to search through for destination opportunities (and origin weighting classes when viewing regional results).  I would even advocate having the default be for attributes not to show up in lists of grids.  Most users will only want a few of the available LODES attributes.  And even when uploading their own shapefiles, users often include extraneous columns like area or population density.

This could also address https://github.com/conveyal/analysis-ui/issues/509

**Comment by ansoncfit** [comment]
See also https://github.com/conveyal/analysis-ui/issues/266

**Comment by abyrd** [comment]
Also, if someone uploads a particular shapefile, then uploads a newer/updated version of the same shapefile, we'll get a new set of grids with exactly the same names. It's then impossible to know which ones came from which input file. A grid management page with creation date and editable names etc. would help a lot here.
