### ISSUE TITLE
Inform users of minimum allowable stop spacing

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#514]
Either with a tooltip that shows up when they try to enter an invalid number, or by re-writing to the minimum or DEFAULT_STOP_SPACING_METERS.

A 50 meter limit seems hard coded into https://github.com/conveyal/analysis-ui/blob/dev/lib/components/modification/edit-alignment.js#L124

**Comment by trevorgerhardt** [comment]
Also, we interpret a "zero" stop spacing right now to indicate that stops are NOT auto-created. ANY stop spacing indicates auto created stops.
