### ISSUE TITLE
Pin icon missing from node_modules

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#523]
I cleared my node_modules and did a fresh `yarn` on `dev`, and I'm missing the leaflet pin icon:

![image](https://user-images.githubusercontent.com/566958/31325165-f451183e-ac6e-11e7-8d82-7b8b0519f5c6.png)

Console:
![image](https://user-images.githubusercontent.com/566958/31325170-040852c4-ac6f-11e7-8e75-70195417b847.png)

No `images` folder in `leaflet/dist`:

![image](https://user-images.githubusercontent.com/566958/31325184-159397e2-ac6f-11e7-85fa-25b5f67d54b7.png)

**Comment by trevorgerhardt** [comment]
Hmmm. Leaflet should have an images directory there. Were there any errors on installation? I just double checked for sanity:

<img width="1186" alt="screen shot 2017-10-09 at 08 15 19" src="https://user-images.githubusercontent.com/776780/31326731-2c3c4ea2-acca-11e7-9bb2-1563935b9e4a.png">

**Comment by primax79** [comment]
leaflet does not install properly with yarn
try with npm


npm install leaflet
