### ISSUE TITLE
No region bounds visible when creating project

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#537]
If I click "set up a new region" the blue boundary rectangle appears briefly and immediately disappears. Without the box there's no way to set up the region boundary. There are no errors in the console. Later upon reloading the page the problem had disappeared, but I had recently hard-reloaded the page just before the problem occurred, so it wasn't caused by stale code.

**Comment by trevorgerhardt** [comment]
Are there any errors in the console when this occurs? Is there a specific way to reproduce this problem?

**Comment by abyrd** [comment]
No, I noted at the time that there were no errors in the console. I don't know of any way to reliably reproduce the problem.
