### ISSUE TITLE
Show more information for completed regional analyses

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#538]
We should display more information for completed regional analyses:
 - R5 version used
 - Egress modes
 - Scenario name used for analysis, potentially linked to downloadable JSON.  We need to figure out how to make sure that if a scenario is updated after a regional analysis has been run, there is a way to figure out what the original scenario was when looking at regional results.

**Comment by ansoncfit** [comment]
We're close to closing this issue, but we need to figure out the last bullet point.

The details table should have a row for "Scenario", and the value should be the name of the scenario.  I propose checking to see if the scenario used for the analysis is exactly the same as the scenario as it is currently specified (using hashes for scenarios?).  If they are the same, the scenario name could link to the modifications page.  If not, I would propose removing the link from the name, and adding a warning icon, with on hover text: "The scenario used to run this analysis has been altered; you can see details in the downloadable analysis log" (see #737)

**Comment by ansoncfit** [comment]
It could be misleading to set the scenario name based on the project Id and variant Index when regional results are displayed, since the scenario might have been renamed or altered since the regional analysis was run.  As an alternative, we could just suggest that the name of a scenario at the time it is run be included in the regional analysis name.

**Comment by abyrd** [comment]
Maybe we should just save the entire request in the regional analysis database entry.

**Comment by trevorgerhardt** [comment]
Closed in #1156
