### ISSUE TITLE
Dragging bounds west past -180 degrees longitude results in invalid values

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#554]
![image](https://user-images.githubusercontent.com/2173529/32663710-f25a2bae-c5fc-11e7-8890-e0cdc6432845.png)

West bound should be +130, not -230.

Not a major issue, as dragging the bounds in the other direction (i.e. crossing the prime meridian) results in correct values.

**Comment by trevorgerhardt** [comment]
This is intended Leaflet behavior (for how they determine bounds) and would require us to normalize it afterwards. Until we have clients whose region crosses the antimeridian it's not worth making a change. Closing as a "wontfix".
