### ISSUE TITLE
Sort Regions, Projects, Scenarios and Regional Analyses

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#569]
Some are sorted by name, some by creation date, some aren't sorted at all. Let's pick one and use that.

Every model will have an `updatedAt` field. We could use that, which would signify the last used item by the client. When they are choosing which one to work on, having that at the top is probably most desireable.

Thoughts @abyrd, @ansoncfit?

**Comment by ansoncfit** [comment]
I would say regions, projects, and regional analyses should be ordered by `createdAt`, with the newest on top.  If we went with `updatedAt`, it could be annoying to have their order changing as different ones were opened/updated.

Scenarios and modifications are currently sorted by `createdAt`, with oldest on top, which I like, especially given the current implementation of numbering scenarios.

**Comment by abyrd** [comment]
Yeah, although it would be nice to have more recently used items on top, it also means they can jump around. I'm not sure how much that would really happen in practice, but sorting by `createdAt` seems good enough.
