### ISSUE TITLE
Allow selecting entire routes

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#57]
Often you want to select an entire route, but the current interface requires you to select all the patterns on that route manually. 

Perhaps we should default to modifying the whole route, and have a checkbox to activate pattern selection. This would also de-clutter the interface when someone wasn't selecting patterns.

This also leads to JSON output that is more human readable: we clearly see that it selects the entire route, not a huge list of trips.

**Comment by mattwigway** [comment]
Was this for a specific modification? This is how most of the modifications work: all patterns are selected initially, and that is exported as modifying the entire route.

**Comment by abyrd** [comment]
Oh. I must have deselected and then re-selected all the patterns. This is not just about using the "routes" field instead of "trips", but also the way the choice is presented. It might be nice to not even display the pattern list until you say you want to select only certain patterns by expanding that widget.

**Comment by trevorgerhardt** [comment]
This has been implemented for adjust speed modifications (and can be for others that need it).
