### ISSUE TITLE
Project does not exist for ID: undefined.

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#570]
On staging, I created a new project, uploaded PBF data, then uploaded a GTFS file, and while it was "processing" the uploaded GTFS I clicked the oppoortunity grid tab with the intent of uploading a shapefile. It immediately threw up the page "Oh no! Looks like an error has occured" with the message "Project does not exist for ID: undefined."

![image](https://user-images.githubusercontent.com/112871/32857417-059ba8ce-ca48-11e7-9b6f-b9b41d6c46ba.png)

**Comment by abyrd** [comment]
I then tried to create a project within this region and got another error: `[ExceptionWhileDataFetching{exception=java.lang.NullPointerException}]`

**Comment by ansoncfit** [comment]
I haven't seen similar errors lately, and it's likely this specific case was resolved by https://github.com/conveyal/analysis-ui/pull/712
