### ISSUE TITLE
Processing started "one hour ago"

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#571]
When an opportunity data set is uploaded and being processed, the UI reports that it started processing "one hour ago" even when it starts processing immediately. Might this be due to a time zone offset between my browser and the server?

**Comment by ansoncfit** [comment]
See also https://github.com/conveyal/analysis-ui/issues/556

**Comment by ansoncfit** [comment]
@trevorgerhardt I think this is resolved, but I don't know which commit is responsible.

**Comment by ansoncfit** [comment]
Resolved as far as I can tell.
