### ISSUE TITLE
Updating modification fields on each keystroke

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#583]
When editing modification titles, descriptions, numeric values, etc., unless a user waits for the spinner to stop between each keystroke, "The data you attempted to change is out of date and could not be updated" is triggered.

Perhaps these fields should only be updated when a user clicks/tabs away?

**Comment by trevorgerhardt** [comment]
A temporary fix was implemented, more work is needed but this will be closed in favor of #589
