### ISSUE TITLE
Use a "Save"/"Apply" button instead of auto-saving

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#589]
Auto-saving has caused problems in the past. Let's do away with it. 

Let's create an obvious "save" or "apply" button that appears or is highlighted when the data has changed that must be manually clicked to save changes. We should also update local state on the fly as that might still be necessary for map/form coordination. 

In instances where a user attempts to navigate away with unsaved changes we should prompt the to either save or discard them. Discarding changes allows for a form of "undo" also, which we do not have currently.

**Comment by ansoncfit** [comment]
Related: https://github.com/conveyal/analysis-ui/issues/544
