### ISSUE TITLE
After loading scenario editing, an extra refresh is needed to load GTFS cache

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#591]
I'm seeing a few issues that seem to be due to the GTFS cache not being loaded after opening the scenario editing page.

For an existing project, modifications won't show up on the map, even after toggling visibility settings, until the page has been refreshed.

For a new project, modifications can't be made.  For add trips, editing alignments does not work because existing stops have not been loaded yet.  For other modifications (e.g. adjust frequency), the select feed dropdown is empty.  Refreshing the page makes things work.

**Comment by trevorgerhardt** [comment]
Is there any logging associated with this? Are there certain projects and bundles this happens to and not others? I have not seen problems of this kind.

**Comment by ansoncfit** [comment]
Nothing shows up in the browser console.

In the server logs (below, from group massdot), sometimes the graphql request to get bundle data only happens after refreshing the page, not when first navigating to it.

First navigating to scenario editing page:
```
18:50:40.031 [qtp558836738-17] INFO  com.conveyal.taui.AnalysisServer - GET /api/project/5c08ba30-2dbf-4fab-883c-c2e67c6378a3 by []
18:50:40.152 [qtp558836738-20] INFO  com.conveyal.taui.AnalysisServer - GET /api/region/988e75d1-49c0-4071-bf66-efb110bd657c by []
18:50:40.300 [qtp558836738-17] INFO  com.conveyal.taui.AnalysisServer - GET /api/bundle/a9e952f238f248f8b523f113d74b88b2 by []
18:50:40.351 [qtp558836738-20] INFO  com.conveyal.taui.AnalysisServer - GET /api/project/5c08ba30-2dbf-4fab-883c-c2e67c6378a3/modifications by []
```

Then refreshing:
```18:51:16.568 [qtp558836738-20] INFO  com.conveyal.taui.AnalysisServer - GET /api/project/5c08ba30-2dbf-4fab-883c-c2e67c6378a3 by []
18:51:16.776 [qtp558836738-17] INFO  com.conveyal.taui.AnalysisServer - GET /api/region/988e75d1-49c0-4071-bf66-efb110bd657c by []
18:51:16.776 [qtp558836738-22] INFO  com.conveyal.taui.AnalysisServer - GET /api/bundle/a9e952f238f248f8b523f113d74b88b2 by []
18:51:17.013 [qtp558836738-21] INFO  com.conveyal.taui.AnalysisServer - GET /api/project/5c08ba30-2dbf-4fab-883c-c2e67c6378a3/modifications by []
18:51:17.338 [qtp558836738-17] INFO  com.conveyal.taui.AnalysisServer - GET /api/graphql by []
18:51:17.339 [qtp558836738-17] INFO  graphql.GraphQL - Executing request. operation name: null. Request:
query dataQuery($bundleId: String, $routeIds: [String]) {
  bundle (bundle_id: [$bundleId]) {
    feeds {
      feed_id,
      checksum,
      routes {
        route_id
        route_short_name
        route_long_name
      }...
```
