### ISSUE TITLE
Scenario editing page should be centered on project or last analysis origin

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#604]
It usually is, but

- click on Set up a new region
- Go back to the main list of regions
- Click on an already created region, then project

The scenario editing interface stays centered on Washington DC. Not a big deal, as this isn't a common sequence, and refreshing the scenario page centers it on Boston.

**Comment by ansoncfit** [comment]
We should also check to make sure the origin marker is within the region bounds on the analysis page.  A user who fetches results when the origin marker is still located in a previous region will see no isochrones and may not realize the origin marker is beyond the map extents.

**Comment by markjd84** [comment]
+1 for this from me :-)

**Comment by trevorgerhardt** [comment]
Regions now center correctly on load 👍 Closed in a past commit...I think from awhile ago :)
