### ISSUE TITLE
Darken selected percentile curve line on cumulative opportunity plot

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#619]

**Comment by ansoncfit** [comment]
We could also display the corresponding accessibility values in the progress bars above.

**Comment by trevorgerhardt** [comment]
This is a nice idea, but I would rather not make the cumulative accessibility plot any more complex.

**Comment by ansoncfit** [comment]
My comment above is implemented -- the progress bars do update to reflect the selected percentile.

I do think the cumulative curves themselves would be much easier to interpret if they somehow reflected the selected percentile. Is the concern about complexity from a user perspective, or from a code/maintenance perspective?

**Comment by ansoncfit** [comment]
Similar comment for the revised box plot introduced in #1183: indicating the value corresponding to the selected percentile (e.g. with a double-width stroke) would make it easier to understand what the displayed numbers to the left of the boxplot represent.
