### ISSUE TITLE
Allow users to download origin point with geojson isochrone

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#627]
This would save some WRI users some time and effort.

**Comment by trevorgerhardt** [comment]
They're asking to add a "Point" feature to the GeoJSON?

**Comment by ansoncfit** [comment]
Yes, so the GeoJSON would be a FeatureCollection, with a Multipolygon for the isochrone and a Point for the origin.  This actually would save me some effort on projects too.
