### ISSUE TITLE
Activity Log

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#639]
We have a variety of ways of reporting status and feedback to the user depending on the actions that are occuring -- a spinner within the button while the user is waiting for a response, an "alert" box indicating something has completed, a "modal" covering the screen for alerts, spinners + progress bars for regional tasks -- and these methods could be consolidated/standardized into a centralized reporting mechanism that could allow us to create more robust logging and give our users more clarity and insight into what is occurring.

For example, when a user is creating a new region the automatic OSM download occuring begins and does not navigate to a "completed" screen even though many actions would be completely reasonable to begin -- creating a project, editing modifications, etc. -- and only running an analysis of any kind on the region is unavailable. Showing feedback of completion of the OSM download only in two places -- within the Create/Edit Region screen and within the Select Region screen -- isn't enough. They either wait for the OSM download to finish (unnecessary waiting) or navigate away manually and are in an uncertain state and may never see the appropriate feedback that OSM download has completed (or an error within the OSM upload/download process). 

The main benefit to a centralized reporting mechanism would be the clarity given in long running processes but a standardized way of reporting general activity (and not just progress) would also become extremely useful for debugging.

So, what would this look like for the user? I envision this in multiple components: 

1. An activity icon/button in the left panel that could show new notifications (i.e. a process has finished)
2. On hover, show a pop-out that shows the text/progress for all active ones. "Regional analyses is x% done".
3. On click, go to a page with a time sorted log of all actions reported. We could set it to only show certain levels of logging and allow a "debug" button to be pushed that would show "all" of the logs, which would be similar to what we see in the console. This could include simple things like "created modification", or "single point analysis with ${x} parameters run". 

From the development side we would want to make it easy to create an "action" or "activity" that would show up in this log. Creating and encapsulating each thing a user does within an "action" would enable us to debug errors much faster. 

Instead of a user sending us a screenshot of a modal with "Error: ${stackTrace}" the actual error is shown after a variety of previous user actions and then shown with context of:

#### Editing Add Trip Modification: ${modificationName}:
 * Remove Timetable: ${timetableName} -- __ERROR: ${stackTrace}__

To do this we'd want to record the start of an activity in the log before attempting it, pass the activity ID through the action sequence so that it can be updated with it's status (started, current progress, error, complete), and possibly save that activity to the database. Synchronizing it on the server would also allow for a more coordinated way for the server to update the status of a variety of activity. 

We would mostly still want to show errors in the same way, with a modal that must be cleared, but it wouldn't be hard to use the same mechanism for activity logging to show those errors.

**Comment by abyrd** [comment]
We might want to look at Data Tools, which has an asynchronous ordered task execution mechanism with progress reporting. It's really reassuring to see those multiple nested progress bars filling up. We might even end up making a shared Conveyal Java library for this.
