### ISSUE TITLE
Selected patterns show up twice

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#640]
Using a locally served copy of current `origin/dev` (commit `51f8a09b073876cdc519f1731bda03a4d4f93dfc`), when I create a "convert to frequency" modification and select a pattern, two copies of that pattern appear in the list of selected patterns. The X on each individual pattern does not delete it. The shared X to the right of the two copies does delete them. See image below.

![image](https://user-images.githubusercontent.com/112871/36026155-bda9b900-0d8d-11e8-9c5b-bb3563337f98.png)

**Comment by Nate-Wessel** [comment]
I am unable to reproduce this bug on the current staging server.
