### ISSUE TITLE
Dragging origin marker sometimes causes destination marker to appear

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#643]
Sometimes when I drag the origin marker in single point mode, instead of moving the origin marker a destination marker appears, with the travel time boxplot popup.

![image](https://user-images.githubusercontent.com/112871/36657709-87bc5810-1b08-11e8-96cf-ebed6d5aeca5.png)

**Comment by ansoncfit** [comment]
In many cases, the destination marker is a distraction.  Perhaps it would be worth having a setting in the analysis panel to enable/disable it.

It would also be good to use a different color for the destination marker, and explain it somewhere in the Analysis panel.  Another option would be to let users drag the destination marker onto the map from a legend.

**Comment by abyrd** [comment]
If it only popped up when a separate click happened, and was indicated with a completely different symbol or color I don't think it would be much of a distraction. We just need to hone the way the UI reacts to certain actions.

**Comment by ansoncfit** [comment]
Testing https://github.com/conveyal/analysis-ui/pull/775, I've observed this issue even when the origin marker is successfully dragged:

![conveyal-analysis---google-chrome-04-oct-18-16_59_14](https://user-images.githubusercontent.com/2173529/46503016-a68e6700-c7f7-11e8-91e7-5c9305c61c49.gif)

**Comment by ansoncfit** [comment]
https://github.com/conveyal/analysis-ui/commit/cb4916e7d199839be72842fad761e7298c29653f fixed this.
