### ISSUE TITLE
Allow import of add-trip modifications that were created using different bundles

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#645]
Currently, the ability to import modifications from another project is restricted to projects that use the same bundle.

It would be useful to be able to import add-trip modifications, either via upload or from projects that use different bundles.  I think this would be fairly straightforward, requiring an update to the `projectId` and the rewriting of all `fromStopId` and `toStopId` values to `null`.

This could also be a step toward more fully replacing the old geom2gtfs, which allowed importing both alignments and stop locations.  We currently only allow alignment import, allowing users to set stop spacing values and requiring them to manually drag stops if they want them in specific locations.

**Comment by evansiroky** [comment]
I assigned myself to this, but if someone else gets around to it, then that's cool.
