### ISSUE TITLE
Bearing arrows are only shown in one direction for bidirectional trips

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#648]
![image](https://user-images.githubusercontent.com/2173529/36703019-bb07d874-1b27-11e8-8355-3977eac41061.png)

The bearing arrows we use are a bit messy, and they confusingly only show up in one direction even when modifications are labeled as bidirectional.  

I think I prefer the style of arrows in Data Tools:

![image](https://user-images.githubusercontent.com/2173529/36703075-fb1c8a86-1b27-11e8-8885-0d8f80407dfe.png)

**Comment by trevorgerhardt** [comment]
There's a reason we showed bearing on the stops instead of the segments, but now that I'm looking at it I can't remember why.

**Comment by trevorgerhardt** [comment]
Well, we show them when it's not bi-directional. Is it necessary to show bearing per stop on a bidirectional trip? Probably not.
