### ISSUE TITLE
Translatable interface

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#65]
We need some string tables. This would also be a good time to address #64.

**Comment by trevorgerhardt** [comment]
Since this is common across our projects I wanted to standardize this too. Was thinking in the configurations we'd have `messages.yml` with everything we need. That file get's converted and can be found with `process.env.MESSAGES` (envify replaces it) so the following code would work:

/configuration/messages.yml
```yml
helloWorld: Hi world!
```

/messages.js
```js
const messages = process.env.MESSAGES
export default messages
```

/index.js
```js
import messages from './messages'
console.log(messages.helloWorld)
```

**Comment by trevorgerhardt** [comment]
@mattwigway see implementation and let me know if you're ok with that.

**Comment by mattwigway** [comment]
Looks good to me. However, have we considered jsgettext? Might be overkill
but it has nice features like stemming, translation tools already available
to work with po files, etc?

Matt

On Tue, Apr 12, 2016 at 8:39 AM, Trevor Gerhardt <notifications@github.com>
wrote:

> @mattwigway <https://github.com/mattwigway> see implementation and let me
> know if you're ok with that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/scenario-editor/issues/65#issuecomment-208884070>
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by trevorgerhardt** [comment]
Haven't considered it seriously mainly because I've never **needed** it and the difference between having two `messages.es.yml` and `messages.en.yml` files loaded in and a proper gettext implementation appears to be an order of magnitude.

What I would see us needing almost immediately is string templates. Adding them in the printf style is simple and we may want to do that for now so we don't need to convert them all to functions in the future.

So if we had 

```yml
category:
  field: Hello %s, today is %s
```

```js
console.log(messages('category.field', 'Matt', 'Tuesday'))
```

**Comment by mattwigway** [comment]
Works for me, and we don't have so many messages that we can't have (say)
separate ones for singular and plural. And we won't be working with
languages that are too weird with things like separate plurals for 2 and
three or more, etc.

On Tue, Apr 12, 2016 at 9:08 AM, Trevor Gerhardt <notifications@github.com>
wrote:

> Haven't considered it seriously mainly because I've never *needed* it and
> the difference between having two messages.es.yml and messages.en.yml
> files loaded in and a proper gettext implementation appears to be an order
> of magnitude.
>
> What I would see us needing almost immediately is string templates. Adding
> them in the printf style is simple and we may want to do that for now so we
> don't need to convert them all to functions in the future.
>
> So if we had
>
> category:
>   field: Hello %s, today is %s
>
> console.log(messages('category.field', 'Matt', 'Tuesday'))
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/scenario-editor/issues/65#issuecomment-208896218>
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by trevorgerhardt** [comment]
Also, with a system this simple moving from it to something more robust wouldn't really be wasting anymore time.

**Comment by mattwigway** [comment]
ok, I'm +1

On Tue, Apr 12, 2016 at 9:15 AM, Trevor Gerhardt <notifications@github.com>
wrote:

> Also, with a system this simple moving from it to something more robust
> wouldn't really be wasting anymore time.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/scenario-editor/issues/65#issuecomment-208899615>
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by mattwigway** [comment]
Most things are in messages now but we still have hardcoded strings scattered throughout the code.

**Comment by trevorgerhardt** [comment]
I'm going to call this issue closed 👌 individual cases can be dealt with in PRs
