### ISSUE TITLE
Allow users to reverse stop order of add-trip and re-route modifications

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#654]
Data Tools has a handy reverse trip pattern feature:
![image](https://user-images.githubusercontent.com/2173529/36993429-ca550d70-207b-11e8-9613-50ffd6dbf4ef.png)

In add-trip modifications, users might want a basically bidirectional route, but with small variations.  It would be nice to draw one direction, copy it, reverse the stop order, then make the small changes.

For re-route modifications that represent extensions, users usually want a bidirectional extension.  But they currently have to draw out stops twice, once per pattern/direction.

**Comment by Nate-Wessel** [comment]
This is also helpful if you draw a bidirectional line and later decide to split it into two directions, for example to phase it with another line. 
Could also help with #949. The reroute geometries do not seem to display a direction property, though they seem to have it when you try to edit them.

**Comment by ansoncfit** [comment]
For add-trip modifications, 
- segments, segmentSpeeds, and dwellTimes arrays need to be reversed
- segments.stopAt{Start/End} need to be switched
- segments.{from/to}StopId need to be switched
- segments.geometry.coordinates array needs to be reversed

Something like:
```
newSegmentSpeeds = segmentSpeeds.reverse()
newDwellTimes = dwellTimes.reverse()

newSegments = []

for(const s of segments.reverse()){
    const stopAtStart = s.stopAtEnd
    const stopAtEnd = s.stopAtStart
    const fromStopId = s.toStopId
    const toStopId = s.fromStopId
    const spacing = s.spacing
    const geometry = s.geometry
    geometry.coordinates.reverse()
    newSegments.push({
        stopAtStart,
        stopAtEnd,
        fromStopId,
        toStopId,
        spacing,
        geometry    
    })
}
```

**Comment by ansoncfit** [comment]
Just discussed as a client priority.
