### ISSUE TITLE
Custom stop spacing not saved when stop creation de/re-selected

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#655]
If I set stop spacing to something other than the default, then uncheck and recheck "Create stops automatically", the default spacing (400m is selected)

**Comment by trevorgerhardt** [comment]
Is this a commonly occuring action or just something we do while debugging? Right now we "detect" if stops are created automatically depending on whether or not the spacing is 0 (no stops) or greater than the minimum (create stops). To save the previously selected spacing would require saving it elsewhere. 

Removed the bug label as this is an intended result.

**Comment by ansoncfit** [comment]
Not common enough to deserve a fix now.
