### ISSUE TITLE
"Initializing compute cluster" persists 

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#666]
The "Initializing compute cluster" message continues to be displayed if you switch to a different project (transport network) or worker version. The message should be specific to the network and worker version selected.

**Comment by ansoncfit** [comment]
On a related note, the spinner in the upper left keeps spinning while a cluster initializes, even when switching to scenario editing mode or a different project.

**Comment by trevorgerhardt** [comment]
Started to look into this today. Do we really want to allow users to "Fetch Results", which sends a task to the broker that requests a worker for the active bundle, and then change projects and do it again repeatedly? Until we separate out the actions, I think the continuous message and spinning are actually appropriate.

But that really just means we should prioritize separating out "get workers for this bundle" and "fetch results" and then show appropriate statuses/messages/spinners accordingly. But that starts on the backend with the Broker/WorkerController.

**Comment by abyrd** [comment]
@trevorgerhardt by "and then change projects and do it again repeatedly", do you mean the user will initiate analyses on multiple projects? My assumption was that we already allowed that course of action, and that the spinner/message continuing to indicate cluster startup when changing to another bundle was a bug. It's not clear when using the system whether it's trying to prevent you from doing work on another project while a worker is starting up.

No matter what we do this is going to be confusing until we can track and report status of all long-running actions separately, as you say at the end of your comment. 

In the mean time though, in the current setup it's definitely problematic that the frontend keeps sending requests over and over by itself, apparently even when you switch to other projects or sections of the UI. We've had to ask customers to close tabs and come back in 10 minutes rather than leaving the tab open because the large number of requests interfere with one another and "clog the broker" for lack of a better explanation. We decided not to waste any more time diagnosing exactly what's going wrong on the broker because the root cause is issuing large numbers of identical, slow/lazy-loading requests that take 10 minutes to an hour to complete.

If there's any way you can remove or disable this automatic re-polling it would eliminate a lot of instability until we can eliminate these long blocking HTTP responses.

**Comment by trevorgerhardt** [comment]
Yes, but if we remove or disable it don't we have to replace it with something? Do we change the button message to "try again in a few minutes"?

**Comment by abyrd** [comment]
I hadn't thought it through thoroughly but I imagine you could just send a request each time the button is clicked, changing the button text or displaying a message when it was still starting up. Of course this serves less of a purpose once I've got the fail-fast HTTP handler working so maybe not worth investing time now, unless it's really easy.

**Comment by abyrd** [comment]
The problem is that the automated re-checking does this quite often and the requests have a tendency to pile up and "clog" the broker for lack of a more precise explanation. It also keeps re-checking when you leave the browser tab open and move on to some other task, and even if you move to some other part of the Analysis UI. It's a very regular occurrence that dozens of these messages pile up and interact badly with the broker or workers, causing lots of extra work or unpredictable actions.

If the user changes projects/bundles and clicks "fetch" again, I don't foresee any problems. I never really realized we were intentionally blocking that, and based on @ansoncfit's comments above I think he considers this something to be "fixed" as well.

I see that we need some kind of throttling or something to discourage clicking "fetch" even more times than it would auto-fetch. 

This is all stopgap, so the simplest thing I can think of that would hold us over is to fire off only one request when hitting fetch. If the cluster is still starting up, disable the button for ~30 seconds or until they change to a different project / bundle, whichever comes first.

**Comment by ansoncfit** [comment]
We're in agreement that a short-term fix is not automatically retrying the request ad infinitum once a user navigates away from the analysis page.

Given the current broker issues, we will also reduce retry interval from every 5s to every 30s.

**Comment by trevorgerhardt** [comment]
Addressed in #800
