### ISSUE TITLE
Allow copying timetables from other modifications

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#675]

**Comment by landonreed** [comment]
In our discussion with some potential clients, I think the ability to have "master" timetables (perhaps at the project or user level) was the more ideal feature than simply copying from another modification.  This would allow for defining a single timetable for a set of "add trip pattern" modifications that could be changed in a single place as scenario requirements changed (e.g., after a discussion in a charrette/planning discussion.  If we are just copying a "weekday high frequency" timetable from pattern to pattern, updating the frequency from 15 minutes to 10 minutes would require a large effort.
