### ISSUE TITLE
Show all selected routes/patterns in modifications

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#696]
For adjust-speed modifications that include multiple routes, only the first route shows on the map and in the printable report.

**Comment by ansoncfit** [comment]
Upon further investigation, it turns out that multiple patterns can be shown on the map, but but only if they have been shown individually first.

To reproduce this:

1. Create an `allowMultipleRoutes` modification (e.g. adjust speed).
1. Select route 1.  It will show on the map.
1. Add to the selection route 2.  It will not show on the map.
1. Remove from the selection route 1.  Route 2 will show on the map.
1. Add route 1 back to the selection.  Both routes will show on the map.
1. But upon refreshing the page or loading the printable report, only one modification will be shown.

**Comment by trevorgerhardt** [comment]
This most likely has to do with how we determine what patterns to fetch using via the GraphQL/GTFS api. I'd look into `actions/get-feeds-routes-and-stops.js`

**Comment by ansoncfit** [comment]
Ah yes, there's an existing TODO:

https://github.com/conveyal/analysis-ui/blob/dev/lib/actions/get-feeds-routes-and-stops.js#L163
