### ISSUE TITLE
Missing mode selectors

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#718]
⛴  FERRY
🚃  CABLE_CAR
🚡  GONDOLA
🚞  FUNICULAR

Mode TRANSIT is no longer sent (after #489; and it wouldn't work in FastRaptorWorker @ 224), so the these modes are excluded from analysis with no way for users to turn them on.  We need ferries for Boston (and probably Gondolas for Portland). I'd be fine with all of these being grouped into one button for "Other"

**Comment by trevorgerhardt** [comment]
It may be just as easy to add all of the buttons as we may get subsequent requests to split them out (for a place like Medellin). Thoughts on this @abyrd?
