### ISSUE TITLE
Project / scenario do not persist in analysis view

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#720]
After refreshing the page, the selected project / scenario are cleared, and they must be reset manually before fetching isochrones.  That could get tedious.

**Comment by trevorgerhardt** [comment]
Do you mean a browser manual refresh? That might not be a common use case we should account for, might just be done in testing. What's a proposed solution? We could store the last project / scenario used and have that selected by default.

**Comment by ansoncfit** [comment]
I think we should store last project/scenario used.

We should also make sure R5 version and opportunity dataset persist

**Comment by ansoncfit** [comment]
Oh, I see now these settings are set by project when I navigate from a project page to the analysis page.

👍
