### ISSUE TITLE
Uploaded opportunity datasets not available in drop-downs

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#732]
On staging, opportunity datasets uploaded as shapefiles or .grid files are successfully processed and uploaded to S3.  But they don't show up in the UI.

**Comment by trevorgerhardt** [comment]
Oi. accessGroup and email got switched. This is a bug on the backend.

**Comment by trevorgerhardt** [comment]
Fixed here: https://github.com/conveyal/analysis-backend/commit/d2c830b5ef290465394f8982a28c712df7194475
