### ISSUE TITLE
Downloadable JSON with regional analysis settings

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#737]
Requested by a users:

"Ability to export a text log file for regional analyses that can assist with documentation (contains key information such as modes, times, simulated schedules, scenarios etc,)"

This ideallly would include the scenario JSON itself.

**Comment by ansoncfit** [comment]
The currently saved scenario json is in R5 format. 

We could also snapshot the modifications in front-end format to allow printable reports.

**Comment by abyrd** [comment]
Saving the modifications in the non-R5 format (used by both the UI and backend) would also be helpful in resolving https://github.com/conveyal/analysis-backend/issues/214. With the new custom modification concept, the possibility exists of modifications that are understood by some version of R5 workers but cannot be deserialized by the backend.

**Comment by trevorgerhardt** [comment]
Closed in #1156
