### ISSUE TITLE
Add "Upload GTFS" button back to "Create Project" screen

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#755]
Not sure when we removed it. Even if there are already bundles there a common workflow might be to click "Create Project" then want to upload a new bundle.

**Comment by ansoncfit** [comment]
I intentionally removed it in response to feedback from WB users.  See third bullet point of https://github.com/conveyal/analysis-ui/pull/707.

If users need to add additional bundles, they should use the bundles tab.  If we're worried this is too much clicking around, it might make sense to have a button at the top of the detail panel for a bundle allowing users to create a project with that bundle.

**Comment by ansoncfit** [comment]
@trevorgerhardt let's decide between this and #791
