### ISSUE TITLE
Always show analysis bounds on map

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#771]
Currently we only show the bounds of the analysis on the map while "set custom geographic bounds" is active. We could just show the bounds all the time (with a non-filled dotted line rectangle or even just the corners). This way there would be no surprise effects when regional analyses were launched (and even on single-points people would visually see if their opportunity counts were being limited to a sub-area). When "bounds of analysis" was set to "same as existing analysis X" the bounds would update, and you would see the bounds rather than waiting until a regional analysis is already running.

**Comment by ansoncfit** [comment]
Current implementation looks like there's a minor off-by one issue:

**Comment by trevorgerhardt** [comment]
It appears we calculate the projection from Coordinates to Pixels differently on the front end and backend. We use `Leaflet.Map.project()` which converts using [this](https://epsg.io/3857) coordinate reference system. The lat/lon to pixel calculations from Grid.java in R5 are handwritten and I'm not entirely sure where from. We should standardize or just send the `north,west,height,width` projected pixels from the UI.

**Comment by trevorgerhardt** [comment]
I noticed this issue last week but assumed once we "snapped" the coordinates to the nearest projected pixel it would be aligned.

**Comment by abyrd** [comment]
@trevorgerhardt as indicated in the Grid.java source code, the conversion functions are from the OSM wiki: `/* functions below from http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Mathematics */`

I think these were written before we were making constant use of the web mercator projection and hadn't researched what library functions were available for this coordinate transform, including the zoom step. 

Is this the case where you said the other day that the off by 1 error was just due to the Analysis backend making bounds that include the input WGS84 rectangle rather than truncating toward zero?

**Comment by trevorgerhardt** [comment]
@abyrd ah yes, I see that comment. I was looking at the `Grid.class` file. 

The requests to Analysis backend come in the form of geographic coordinate bounds and get converted to pixel coordinates before being sent to R5. I originally thought the difference we were seeing was in the `Grid.java` constructor that adds 1 to the height and width after converting which we were not previously doing. But that was for the purpose of creating appropriately sized arrays to represent all of the coordinates.

The actual conversion functions convert to different pixel points on the front end and backend and do not appear to be in a way that can be corrected by just "adding one" as all four coordinate edges can be off to varying degrees. I'll attach a screenshot in a bit...

**Comment by trevorgerhardt** [comment]
<img width="294" alt="screenshot 2018-10-16 14 13 50" src="https://user-images.githubusercontent.com/776780/46996086-f3563400-d14d-11e8-8f95-d847cf3c782e.png">

**Comment by trevorgerhardt** [comment]
One option is to send the exact north, west, height, width from the UI so that the projection is done there.

**Comment by trevorgerhardt** [comment]
Good call, porting over the calculations from the backend wasn't too difficult 👍

**Comment by trevorgerhardt** [comment]
<img width="445" alt="screenshot 2018-10-16 18 21 05" src="https://user-images.githubusercontent.com/776780/47009935-43de8900-d170-11e8-9a86-01b5a6bdde0e.png">

**Comment by trevorgerhardt** [comment]
This also requires change in `jsolines`

**Comment by abyrd** [comment]
Please be sure to include a comment about where they came from (link to OSM and backend both, ideally).

**Comment by Nate-Wessel** [comment]
I think the resolution to this issue may have been a bit narrow. At present, you can still only see the region/analysis bounds 
a) when directly editing them and 
b) in the single-point analysis tab. 
They would definitely be helpful when editing modifications as well and should probably just be visible at all times for consistency and context. Issue #969 discusses providing more consistent context for the user on their place in the region->bundle->project hierarchy. IMO, this would help that.

**Comment by Nate-Wessel** [comment]
It seems like the bounds shown on the analysis page (dashed light blue box) are not always updated quickly when the bounds are changed on the region settings page. Sometimes a hard page refresh will make the analysis page show a new updated region boundary, but then when an analysis is run, the old bounds will reappear and limit where I can set the origin point.

**Comment by Nate-Wessel** [comment]
This would also be very helpful when looking at opportunity datasets e.g. those created by the LODES import. As it is, it can be very hard to figure out whether opportunities have been clipped off at the regions bounds or if they just trail off.

**Comment by Nate-Wessel** [comment]
> It seems like the bounds shown on the analysis page (dashed light blue box) are not always updated quickly when the bounds are changed on the region settings page. Sometimes a hard page refresh will make the analysis page show a new updated region boundary, but then when an analysis is run, the old bounds will reappear and limit where I can set the origin point.

This may be because the original region boundary gets set as a custom analysis area. Selecting the whole region for the analysis updates the bounds correctly.
