### ISSUE TITLE
Stop fetching R5 build list from S3

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#781]
It's incredibly slow and is now 191kb of text. 

To change this in "normal mode": 
* We should only allow usage of any r5 builds that have been previously used and the default.

In "advanced mode":
* We should allow typing in text directly for any build. It's up to the user to know which builds there are.

Thoughts @abyrd and @ansoncfit?

**Comment by abyrd** [comment]
Makes sense to me @trevorgerhardt - for special builds (advanced modes) we can just allow free-text JAR file names from the user. 

How will we prime the list in "normal mode" though? A list of predefined version strings in the config file? When you say "r5 builds that have been previously used", where would this memory be - on the backend, in the browser's data?

**Comment by trevorgerhardt** [comment]
In "normal mode" we would just have the single recommended version encoded to use and then populate the list of previously used versions from regional analyses that have been previously run.

**Comment by abyrd** [comment]
Ah I see, from the previously run regional analyses. Makes sense.
