### ISSUE TITLE
regeneratorRuntime is not defined and mastarm version needs updating

### ISSUE THREAD

**Issue by stites** [conveyal/analysis-ui#792]
Hi there,

I just tried following the instructions on a couple of machines and wound up hitting a couple of bugs:

- On the `dev` branch with node 10, mastarm 3.10 complains about not having node version `"6"`. It also complains about the node version if it is node 6.14. This is fixed in the latest version of mastarm. I am using binaries from nixos, so dropping into `nix-shell -p yarn -p nodejs-6_x` can be used to simulate this behavior. `yarn upgrade mastarm@4.4.1` fixes this for me.

- On `dev` branch, and also on 4.2.0, I'm also seeing some missing dependencies (I think `core-js`). I think this needs to be checked in. Error message on 4.2.0 below. `yarn add core-js && npm install && npm start` makes this go away.
```
[0002]  info  Server running at http://10.0.0.130:9966/ (connect)
updated assets/index.css
updated assets/index.css
Error: Cannot find module 'core-js/modules/es7.symbol.async-iterator' from '/home/shared/git/conveyal/analysis-ui/lib'
```

- Now, on release 4.2.0 with mastarm@4.4.1 and node 10, I'm seeing the following ` regeneratorRuntime is not defined` error. I think it means that, [according to this SO question](https://stackoverflow.com/questions/28976748/regeneratorruntime-is-not-defined), I am missing some sort of babel dependency which is globally installed on CI and dev machines(?).
```
ReferenceError: regeneratorRuntime is not defined[Learn More] index.js:18985:1
[97]</TransitEditor</<.value<http://localhost:9966/assets/index.js:18985:1
[97]</TransitEditor<http://localhost:9966/assets/index.js:18982:12
[97]< http://localhost:9966/assets/index.js:18299:1
o _prelude.js:1
o/< _prelude.js:1
[90]< index.js:31
o _prelude.js:1
o/< _prelude.js:1
[142]< modifications-map.js:9
o _prelude.js:1
o/< _prelude.js:1
[67]< editor.js:13
o _prelude.js:1
o/< _prelude.js:1
[141]< modification-editor.js:15
o _prelude.js:1
o/< _prelude.js:1
[197]</< routes.js:24
[197]< http://localhost:9966/assets/index.js:28006:2
o _prelude.js:1
o/< _prelude.js:1
[159]< index.js:5
o _prelude.js:1
r _prelude.js:1
<anonymous> _prelude.js:1
```

---

Steps to reproduce (with nix-shell):
```
# <remove global npm installs or create a clean user>
# git clone git@github.com:conveyal/analysis-ui.git
# cd analysis-ui
# nix-shell -p nodejs-10_x -p yarn
(nix) # yarn upgrade mastarm@4.4.1
(nix) # yarn add core-js
(nix) # npm install && npm start
```

**Comment by trevorgerhardt** [comment]
Simple answer is that you need to run with node version 6.x.x. It's currently running locally for me with node version 6.14.1 and passing tests on TravisCI for [v6.14.4](https://travis-ci.org/conveyal/analysis-ui/jobs/442622115#L449). Stating that "also complains about the node version if it is node 6.14" is not enough information to debug but that's where we should start.

The mastarm and node version update is not that simple and will not be happening anytime in the next couple of weeks. There are at other issues that need to be accomplished before we update (see https://github.com/conveyal/analysis-ui/milestone/9) and a big one not listed is fixing all of the `flow` errors that occur.

**Comment by trevorgerhardt** [comment]
Related, but not for this issue, our recent changes to `mastarm` might be causing the regeneratorRuntime error as the `useBuiltIns: "usage"` flag doesn't appear to be working correctly: https://github.com/babel/babel/issues/8829

**Comment by stites** [comment]
Thank you @trevorgerhardt, I rarely end up in the web world these days and this was helpful. I managed to get past these issues with nodejs 6, mastarm 3.1.0, and installing yarn through npm (instead of using nixos' default yarn which, I think, is built with node 8). I'm hitting another bug in some templating generation, but I think I can close this issue for the time being.

Thanks again!
-s
