### ISSUE TITLE
Opportunity dataset id, instead of name, shown on regional analysis results pages

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#796]

**Comment by trevorgerhardt** [comment]
In all cases?

**Comment by ansoncfit** [comment]
After navigating directly to a regional analysis URL (https://analysis-staging.conveyal.com/regions/5bea0a4b32b98e195f6cfa13/regional/5beb25ae32b98e53965828d8) or refreshing:

![image](https://user-images.githubusercontent.com/2173529/48584025-b15c1180-e8f6-11e8-9ad8-5edbb1fae8d5.png)

After navigating to another page (e.g. manage opportunity datasets) --> regional analysis list --> regional analysis, the name shows up:
![image](https://user-images.githubusercontent.com/2173529/48584122-ec5e4500-e8f6-11e8-8c53-126392e305fc.png)
