### ISSUE TITLE
Copy Timetable - make direction of copy clear

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#822]
The dialog for Copy Timetable does not make it clear that it's copying from the timetable selected in the dialog into the modification currently being edited. I at first wondered if it was copying from the timetable currently being edited into the one selected in the dialog (the opposite direction). A change of dialog title and explanatory text would help here.

**Comment by Nate-Wessel** [comment]
We probably just need to change "Copy timetable" (below) to "Copy existing timetable". 
![Screenshot_2020-01-15_12-33-54](https://user-images.githubusercontent.com/7830465/72456869-7fad3780-3793-11ea-9228-60c83e0f1afd.png)
Perhaps the "Add timetable" option should also be changed to "Add new timetable" for extra clarity.

The dialogue that comes up when you click that already says "Copy into new timetable", which seems clear enough.
![Screenshot_2020-01-15_12-35-56](https://user-images.githubusercontent.com/7830465/72456986-b5eab700-3793-11ea-8f1a-6f8b546ba67b.png)
