### ISSUE TITLE
Add-stops modification: allow multiple reroutes within a single modification?

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#83]
When you add stops to a route, you often need to modify both directions of that route. It feels weird to create multiple modifications on the same route just to handle both of the opposing directions.

**Comment by mattwigway** [comment]
The problem is that multiple directions tend to have completely different stops (on opposite sides of the street etc.). Fixing conveyal/r5#114 will help, but I'm thinking we may also need to specify start and end stops of a reroute as arrays, and allow reroutes to be applied backwards.

**Comment by mattwigway** [comment]
@abyrd my position on this is that rerouting both directions of a route simultaneously is complicated and prone to error, so I'd be in favor of closing this. Thoughts?

**Comment by mattwigway** [comment]
Let me know if this is still desirable @abyrd, otherwise I'll close it.

**Comment by abyrd** [comment]
This is probably not necessary. I think the core issue is re-use of the frequency entries. It would be nice to define the service in both directions at once. But the inherent complexity of creating two modifications instead of one is not that terribly different.
