### ISSUE TITLE
Re-enable bike egress

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/analysis-ui#850]
For R5v4.6.1 and up

**Comment by ansoncfit** [comment]
Depends on https://github.com/conveyal/r5/issues/426

**Comment by ansoncfit** [comment]
Just discussed: we can now re-enable bike egress in advanced settings, but we'll want to keep the egress mode WALK even when access mode is changed.  Also, given planned changes to R5, we'll want to display a notification that changing to a non-WALK access mode may require extended computation, so contact support team if needed.
