### ISSUE TITLE
Modifications not shown consistently

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#858]
1. Click 👁 next to a scenario name to display modifications in that scenario
2. Navigate to Analyze mode
3. Navigate back to Edit Modifications mode. A different set of modifications is shown on the map.

**Comment by ansoncfit** [comment]
@trevorgerhardt and I just discussed storing visibility settings in the browser, rather than the database.

**Comment by trevorgerhardt** [comment]
This should be fixed 👌
