### ISSUE TITLE
Check for discontinuous segments

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#859]
Multiple users have reported modifications that fail the new segment continuity check introduced at https://github.com/conveyal/analysis-backend/pull/205/files#r268611704

I've been using the code below to search for discontinuous segments.  Nudging a control point at the problematic segments seems to fix the modification and allow it to pass the segment continuity check.  

I noticed the discontinuities seem to arise at control points where alignments change from follow-street to straight-line.

```
modifications.forEach(mod => {
	if (mod.type == "add-trip-pattern"){
	for (i = 1; i < mod.segments.length; i++){
		prevSegCoords = mod.segments[i-1].geometry.coordinates
		thisSegCoords = mod.segments[i].geometry.coordinates
		if (prevSegCoords[prevSegCoords.length-1][0] !== thisSegCoords[0][0] ||
			prevSegCoords[prevSegCoords.length-1][1] !== thisSegCoords[0][1]
		){
			console.log(mod.name + ", segment " + i)
        }
	}}
})
```

**Comment by trevorgerhardt** [comment]
There is now a clearer error message to help users determine which segments are discontinuous. Solutions for solving this for a user were too intrusive and would change the modification out from underneath them. Closing for now as a `wontfix` unless more users are having trouble solving.
