### ISSUE TITLE
Option to use features of uploaded shapefile as aggregation areas

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#862]
When a user uploads an aggregation area, analysis creates a single aggregation area (the union of the uploaded shapefile).  For some use cases (e.g. uploading a shapefile of neighborhoods or city council districts), it would be helpful to have each feature available as a separate aggregation area.

**Comment by ansoncfit** [comment]
Requires https://github.com/conveyal/analysis-backend/issues/212

**Comment by trevorgerhardt** [comment]
What was the resolution on this? Are we adding the option to "union" or just turning that off? @ansoncfit

**Comment by ansoncfit** [comment]
We agreed to add the "Union" checkbox option, set to true by default.  Suggested explanatory text:

"If unchecked, a separate aggregation area will be created for each feature (up to 60) in the uploaded shapefile"

**Comment by ansoncfit** [comment]
Also note `name` and `nameAttribute` in the relevant backend changes
