### ISSUE TITLE
Multiple collapsible profile requests

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#866]
Currently, two isochrones can be displayed with the only difference being the scenario vs. comparison scenario. It would be helpful to be able to superimpose isochrones reflecting differences in other profile request parameters (e.g. access modes, departure time window, reliability percentile, etc.)

**Comment by ansoncfit** [comment]
Idea from @abyrd related to how display results chart in a unified way once settings for each request have been split out:
> Display destination travel time box-and-whisker bar below the cumulative opportunities plot, reusing its time axis (instead of in a popup). With reverse-geocoded name?

**Comment by trevorgerhardt** [comment]
Closed in #1097
