### ISSUE TITLE
Fields not editable

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#871]
On staging, in the default timetable for an add-trip modification, the frequency and dwell time fields cannot be modified.

**Comment by trevorgerhardt** [comment]
Are there any related console errors?

**Comment by ansoncfit** [comment]
No console errors. You can observe this with any new or existing add-trip modification on staging (e.g. https://analysis-staging.conveyal.com/regions/5a2e9df732b98e221fef89eb/projects/5b75bc5632b98e0ee389f9c7/modifications/5c131bbb32b98e5d92c601e6)

**Comment by ansoncfit** [comment]
Also on staging, the project name field in project settings cannot be updated.
