### ISSUE TITLE
Are the releases version stables ?

### ISSUE THREAD

**Issue by brunetton** [conveyal/analysis-ui#872]
Hi, I'm working on the Dockerisation of analysis. I managed to make all work great using last commits versions of backend and ui but when I reset to last tagged version (ie backend v5.4.0 and ui v4.7.0) I get a blank page for ui and nothing in logs.

Can you confirm this too or maybe I missed something ?

So I'm wondering: to distribute a Docker image, what's the best versions of ui and backend to use ? HEADs of the two repos or last tagged versions ?

Thanks !

**Comment by trevorgerhardt** [comment]
Hi @brunetton, versions should work but we have no outward recommendations.

> Please note that Conveyal does not provide technical support for third-party deployments of Analysis. We provide paid subscriptions to a cloud-based deployment of this system which performs these complex calculations hundreds of times faster using a compute cluster. This project is open source primarily to ensure transparency and reproducibility in public planning and decision making processes, and in hopes that it may help researchers, students, and potential collaborators to understand and build upon our methodology.
