### ISSUE TITLE
Specify patterns instead of exhaustive list of trips in scenario editor output

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#89]
We currently specify an exhaustive list of all trips on the patterns of interest in the trips field of the modification output. After discussion with @abyrd, we agreed to instead specify whole patterns, still as a list of trips, but without needing to list every trip on a pattern; one trip per pattern will suffice.

So what needs to change immediately is that the `trips` field needs to change names to `patterns`. Longer-term, we need to change out the way the pattern selector works so that it only puts a single trip per pattern in the patterns array. This should simplify the code significantly.

**Comment by mattwigway** [comment]
We now write out a patterns field instead of a trips field. It's still listing all trips on the patterns exhaustively though.

**Comment by abyrd** [comment]
One potential problem: R5 splits trips into patterns based on stop sequence, but also pickup and dropoff type. The scenario editor will need to include one trip per pattern following this definition, not just one trip per stop sequence.

**Comment by mattwigway** [comment]
We've also talked about splitting patterns in r5 so that patterns cannot have both frequency and scheduled trips.

What we should do is adapt the findPatterns method in gtfs-lib, and then use it both places. We'll have to consult with @landonreed though to ensure we're not causing pain elsewhere.
