### ISSUE TITLE
Isochrones are misaligned with region edge

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#923]
Vector isochrones cut off at the edge of the region are misaligned with the region boundary show in the UI.

**To Reproduce**
1. Request an isochrone at the very edge of the region.

**Expected behavior**
The isochrone should cut off at the region boundary, not slightly before/past.

**Screenshots**
![image](https://user-images.githubusercontent.com/566958/65738727-b1d94300-e097-11e9-9260-ba5026dae59a.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Chrome
 - Version 77

**Additional context**

**Comment by mattwigway** [comment]
I don't think I assigned Trevor to this...

**Comment by abyrd** [comment]
Thanks for the report @mattwigway. I'm not sure why it says you assigned Trevor, we might have some automation in place that does that. As mentioned in conveyal/analysis-backend#243, we'll be testing for a release this week so we'll check it out.

**Comment by Nate-Wessel** [comment]
I think this was resolved in #771. I wasn't able to reproduce the problem. 
![Screenshot_2020-01-15_12-27-23](https://user-images.githubusercontent.com/7830465/72456388-90a97900-3792-11ea-8922-0c1c830cbc9a.png)
