### ISSUE TITLE
Saving region allowed with invalid bounding coordinates

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#944]
It's possible to save the region settings (region settings tab) with invalid bounding coordinates entered. I tried entering a northern bound of 4000 and hit save. The map clipped the bounding box to 90N but the change didn't seem to have saved after a few minutes of waiting. 
I also tried saving various non-numeric coordinates and got either an error report or a blank screen. 

Since it seems like there is already some JavaScript validation on the form fields, I'd suggest avoiding this problem by disabling the save button when the form is in an invalidate state. It's already disabled if no changes have been made to previously saved values. 

As seen on Firefox 71.

**Comment by ansoncfit** [comment]
Worth noting that `NumberInput` components can have `min` and `max` values (see fix for #857). But as we just discussed, there may have been better logic in the past that was lost.
