### ISSUE TITLE
Scenarios should use names as well as numbers when editing modifications

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#948]
When editing a modification, one is able to choose between scenarios in which the modification will be active. These are visibly identified only by a number, though they also have a name which can be shown by hovering over the checkbox, i.e. the name is already stored in the `title` attribute. 

The name is much more important than the number, which is generated automatically and may be hard to remember. Thus, I think it would be better for the scenario checkboxes to be stacked vertically with the name and number printed to the right. e.g.
* [x] 1. First Scenario Name
* [ ] 2. Second Scenario Name

**Comment by ansoncfit** [comment]
LADOT just made this same observation. Let's prioritize.
