### ISSUE TITLE
Clean up time entries

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#954]
Two observations:
1. When editing frequency or dwell time fields, I often select the minutes digits and type to replace them.  But (in Chrome on Windows) the cursor jumps to the end of the field after I start typing, so I need to delete the seconds fields and retype things:

![image](https://user-images.githubusercontent.com/2173529/71300037-61941900-2346-11ea-92d0-84a4bc2086c2.png)

2. US users may be inclined to enter times (e.g. from/to times in the analysis panel) without the leading zero.  We may want to allow that.

**Comment by ansoncfit** [comment]
See also #965

**Comment by trevorgerhardt** [comment]
I believe this is fixed. Could not reproduce on staging
