### ISSUE TITLE
Time input fields in timetable window too quick to correct format

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#965]
When adding a schedule to a new trip pattern, the time input fields can be a bit too aggressive at correcting the format of the input. For example, let's say I want to change the default frequency value of `00:10:00` to `00:30:00`. I try to do this by placing my cursor after the `1`, deleting it, and adding `3`. But by the time I type `3`, it's moved my cursor to the end and I wind up with `00:00:03`. 

It will also often overshoot at the end. I.e let's say I try to make the change by deleting characters from the end until I just have `00:`. I'll then enter the remaining `30:00` but wind up with `00:30:000`.

I'm guessing that whatever form validation is going on here probably just needs to be moved from an `onchange` to an `onblur` event to let the user finish typing before making corrections.

**Comment by Nate-Wessel** [comment]
There is an interesting dynamic when trying to set the total moving time in particular. I try to delete the final digit and it seems to instantly autofill that digit to zero. This updates the average segment speed to a rounded value which then itself updates the total total moving time again. 

I try to delete a seconds digit and the whole value changes, even in the minutes field.

**Comment by Nate-Wessel** [comment]
This is a problem in Cypress tests as well. I have it type something like `00:10:00` and end up with `00:10:000`. It seems to save correctly though, dropping the final digit, so tests are still passing.

**Comment by trevorgerhardt** [comment]
@Nate-Wessel just pushed a change that should address this. Let me know if that helps!

**Comment by Nate-Wessel** [comment]
@trevorgerhardt That seems to resolve this issue completely. Thanks!
Once those changes get merged in we can close this issue.

**Comment by Nate-Wessel** [comment]
This seems to have become an issue again (or maybe it wasn't completely fixed?)

I'm having trouble specifically with the three digit fields in timetables (`00:00:00`) autocorrecting while I type, while the two digit fields (`00:00`) are working fine.
