### ISSUE TITLE
"Could not find existing stop" errors with phased trip patterns

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#966]
I was trying to test the phasing options by creating a simple, branching, frequency-based line. Each branch should run with a thirty minute headway to make a combined 10 minute headway on the shared trunk. 
During analysis I get the following errors: 
![Screenshot_2020-01-08_10-28-48](https://user-images.githubusercontent.com/7830465/71990942-4ceac880-3202-11ea-855d-a00062ae10dd.png)
The new route, constructed of three *add trip pattern* modifications is the only addition to the baseline scenario. The three trip patterns reuse three stops from the GTFS bundle, one of which is selected for phasing. It appears that none of the reused stops can be found. 

The baseline scenario works fine in analysis. 

The region/project is: https://analysis-staging.conveyal.com/regions/5df14ce26844a22caafc8557/projects/5e14ba280b4f073985ec2d51

In case this is relevant I created the first modification and timetable manually and then copied it to create a second branch which I modified and so on.

**Comment by Nate-Wessel** [comment]
I wondered if perhaps this had to do with the GTFS being out of date for the analysis. I.e. that the stops were not found because they weren't used in any current service. I tried pushing the analysis window back a month though and I still get the same error. 

It occurs to me now that there is no way to check the dates on a bundle once it has been uploaded.

**Comment by Nate-Wessel** [comment]
Probably related to #970.

**Comment by trevorgerhardt** [comment]
@Nate-Wessel can you confirm this behavior occurs on production?

**Comment by Nate-Wessel** [comment]
I can reproduce the problem on staging, but not production.

**Comment by abyrd** [comment]
I believe this is fixed on staging, please let me know if you see anything similar.

**Comment by Nate-Wessel** [comment]
This is fixed.
