### ISSUE TITLE
Preface project names with bundle name

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#969]
I've been trying to think through how to better explain projects and how they're related to GTFS bundles. My understanding is that a project is essentially just a named link attaching modifications and scenarios to a baseline GTFS bundle. With a single user, there's no need for projects since modifications could be attached directly to the bundle and grouped/managed with scenarios. The project comes in as a way of managing potential editing conflicts when there are multiple users needing to work with the same bundle.

If this is the case, then the convention of naming the bundle and the project separately seems to introduce either repetition (e.g. both names contain agency/region name information) or potential confusion (e.g. the project name does not clearly reference the bundle). 

I'd like to suggest that project names, when shown, should always be prefaced with the name of the bundle they are attached to. I.e bundle as context or namespace. 

So for example, let's say I upload a new bundle with two feeds, one for TTC, one for GO transit. I name the bundle `TTC+GO Winter2020` indicating the agencies and approximate time period of the feeds. We have two people working on modifications - one is editing the rail network, one is editing bus lines [as suggested in the docs](http://docs.analysis.conveyal.com/en/latest/edit-scenario/index.html#usage-suggestions-and-details). We might try to name the two projects `rail` and `bus`, but this doesn't distinguish them clearly from projects based on other bundles. We could name them `TTC+GO Winter2020 - rail` etc. but this is essentially just typing that out twice and there might eventually be slight differences or users who don't follow the same naming convention. 

It seems clearer to me to think of the projects as only needing distinct names within the context of the bundle they point to. Thus, my project names might be:

* TTC+GO Winter2020 | Rail
* TTC+GO Winter2020 | Bus
* TTC+GO Winter2020 | Bus + Rail Combined 
* TTC+GO Spring2020 | Rail
* TTC+GO Spring2020 | Bus

This could also allow project names to be left blank. 

* TTC+GO Summer2020 

Which would sort of hide the fact that there is this potentially unnecessary project layer between the user and the bundle.

Is there a context or use case where enforcing this wouldn't make sense and add clarity?

**Comment by abyrd** [comment]
Thanks for sharing your observations. First just to give some background: even for a single user, a project is a way to group modifications/scenarios, and that single user could have more than one project referencing the same GTFS. Some users could have dozens of different projects all referencing the same GTFS, with each project containing modifications that aren't meant to be combined with those from other projects. A scenario is then a particular combination of modifications from one project.

For a user that is doing several different projects, it's not uncommon to upload one GTFS, maybe for an entire country, and reuse that GTFS for N totally unrelated projects, maybe even for different clients, whose modifications should not be mixed together. 

I can see how it seems redundant when you have one region with one bundle, one project, and one or two scenarios, but these multiple layers grew out of experience with transit agencies or consultancies working on multiple larger projects in the same geographic area.

All that said, I would definitely agree that the project name should be shown (in fact probably both the region and project name) at all times to give context for the project/scenario you're currently working on. I see this as a display / presentation question and not something we'd carry over to the names of the underlying objects. So we wouldn't be enforcing a scheme for naming projects, but just making sure the full "path" was always displayed so you'd never need to repeat phrases when naming sub-items like projects or scenarios.

**Comment by Nate-Wessel** [comment]
Thanks for the context @abyrd. 
I guess I should clarify that I didn't mean to imply that any naming convention should be enforced for the user, but that we should commit to a consistent display context which would lend itself to more concise project names. 
I agree though that this is probably a somewhat broader issue. For example I hadn't realized that the region name isn't displayed at all times until I checked just now.

**Comment by trevorgerhardt** [comment]
Is the problem while selecting the project or while editing the project? We could quite easily display the bundle name next to the project name.

ex:

<img width="319" alt="Screen Shot 2020-01-14 at 11 56 12 AM" src="https://user-images.githubusercontent.com/776780/72313002-df88dd00-36c4-11ea-9832-b338d7a45efe.png">

**Comment by Nate-Wessel** [comment]
@trevorgerhardt that looks great! I think that anywhere you may see a project name, you should see the bundle too. So:
_Projects_ (as in youur screenshot above)
_Edit modifications_ (where projects can be selected and where the project name is listed at the top)
_Analysis_ (where projects are selected from dropdown menus)

And _Regional Analysis_ where this is already given:

![Screenshot_2020-01-14_09-22-53](https://user-images.githubusercontent.com/7830465/72352081-99754e80-36af-11ea-97fd-ba930cea134d.png)
