### ISSUE TITLE
Bottom half of map display sometimes doesn't load / isn't shown

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#971]
I haven't yet figured out what might be causing this, but it sometimes happens that the bottom half of the map display doesn't load or is covered by a grey element. I've seen the problem in both Chrome and Firefox (screenshots below, respectively) multiple times. 

![Screenshot_2020-01-11_11-31-11](https://user-images.githubusercontent.com/7830465/72207335-38a70580-3466-11ea-8c91-5504d5b7ab0e.png)

![Screenshot_2020-01-11_10-09-36](https://user-images.githubusercontent.com/7830465/72207337-3c3a8c80-3466-11ea-9b5a-ddec6b567795.png)

When this happens, the map always stops at about the same position ~3/5 of the way down the window. It doesn't seem to be related to a Y tile boundary, because I can sometimes drag the map and the map will smoothly appear/disappear when it crosses that point on the screen. 

The problem always seems to fix itself after a little interaction. In particular, adjusting the window size e.g. by opening the console to debug. Navigating to a new page generally seems to fix it as well.

**Comment by Nate-Wessel** [comment]
A couple more notes: 

This does seem to happen consistently after selecting a new region, but it happens at other times as well. 

When there are modifications on the map and they are dragged below the break, they may be visible in the grey area though the basemap isn't.

**Comment by ansoncfit** [comment]
Reopening for a similar issue:


![image](https://user-images.githubusercontent.com/2173529/73028301-3f892d00-3e03-11ea-9e98-0ab1ecdb2fcb.png)

Both the map and the sidebar are clipped at the bottom.

To reproduce in Chrome at https://analysis-staging-git-fix-phase.conveyal.now.sh/regions/a87eb73e-ca9f-48c2-9874-27b1e677b0e6/projects/5e2a17af84ddf4619ec79d4d/modifications/5e2a191284ddf4619ec79d54,
Add a frequency entry, select a pattern, select a phase at stop.

**Comment by ansoncfit** [comment]
Related issue still occurring (e.g. at https://analysis-staging.conveyal.com/regions/a87eb73e-ca9f-48c2-9874-27b1e677b0e6/projects/5e2a17af84ddf4619ec79d4d/modifications/5e3250b17d0f5225fe0696c7)
