### ISSUE TITLE
Regional Analysis comparison map not centered on Zero, extends beyond region bounds

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#973]
In the regional analysis comparison map, zero (difference in accessibility between scenarios) seems to be treated just like any other number and gets lumped in with other values in what seems like a quantile binning scheme. The documentation indicates that the legend should be centered on zero though with higher relative values in blue, lower in red. 

One of the side effects of this seems to be that whatever bin contains zero extends across the entire map, and actually also beyond the region bounds as in the screenshots below.

![Screenshot_2020-01-13_10-21-10](https://user-images.githubusercontent.com/7830465/72267686-80589900-35ee-11ea-99d9-18ad57043d3c.png)

![Screenshot_2020-01-13_10-22-59](https://user-images.githubusercontent.com/7830465/72267875-c9105200-35ee-11ea-9acc-8ea22ad8a798.png)

Zero should not be binned with other values and should display as fully transparent. 
There should probably also be a region bounding box shown on the map and there definitely shouldn't be any values rendered beyond it.

**Comment by trevorgerhardt** [comment]
It's fairly straightforward to change the colorizer to make all 0's fully transparent. It appears to cause some streaks in the images produced. But they're really not too extreme.

Thoughts? 

<img width="1552" alt="Screen Shot 2020-01-16 at 6 46 54 PM" src="https://user-images.githubusercontent.com/776780/72518600-adc47180-3890-11ea-9bb3-aac78505cb4e.png">

<img width="1552" alt="Screen Shot 2020-01-16 at 6 46 13 PM" src="https://user-images.githubusercontent.com/776780/72518597-ad2bdb00-3890-11ea-8e9f-5c006df1c6a6.png">

@ansoncfit implementation wise I think #472 is a fairly different issue.

**Comment by trevorgerhardt** [comment]
Hmmm, I might be implementing the change at the wrong level which would cause the streaks. Let me investigate more.

**Comment by Nate-Wessel** [comment]
@trevorgerhardt it's definitely an improvement, but I think we really need to treat zero as a break-point in the color scheme. Negative values below increasingly red, positive above increasingly blue. That also makes anything adjacent to zero values a more muted, neutral color, so any weird pixelation or other boundary effects would appear more muted.

**Comment by trevorgerhardt** [comment]
It is quite strange to have negative and positive numbers in one bin. We selected the colors less for negative vs positive and more just for a contrasting color scale.

It would be quite easy to increase the total breaks to six, with three being positive and three being negative. I'm not entirely sure what the repercussions would be for our users though.

Thoughts, @abyrd and @ansoncfit?

**Comment by trevorgerhardt** [comment]
Proposed solution -- compare the absolute value of positive vs negative values and bin to the maximum side. Then duplicate the bin sizes on the opposing side.

Impose a transparent area in the bins next to 0 when there are monte carlo draws. Use the lighter tone when there are not.

**Comment by trevorgerhardt** [comment]
Using https://github.com/d3/d3-scale-chromatic we can generate the colors and breaks on the fly. 

We currently have 5 breaks. When the center color is not transparent we can still use five breaks. When it is transparent we should up it to six breaks so there would be an even amount of colors on either side of the transparency.

**Comment by trevorgerhardt** [comment]
Ok, this is starting to look a lot better.

### Zero values transparent 
(new screenshots are first)

<img width="1532" alt="Screen Shot 2020-01-20 at 10 00 55 AM" src="https://user-images.githubusercontent.com/776780/72694310-8e1e9900-3b6f-11ea-8a75-5491e2963a63.png">
<img width="1532" alt="Screen Shot 2020-01-20 at 10 01 01 AM" src="https://user-images.githubusercontent.com/776780/72694311-8eb72f80-3b6f-11ea-9b21-9563134bb5d3.png">

### With comparison:

Notice that the transparent band overlaps 0. Need to find a regional analysis that shows similar amounts of negative and positive to get a better feel.

<img width="1552" alt="Screen Shot 2020-01-20 at 10 26 05 AM" src="https://user-images.githubusercontent.com/776780/72694350-a8f10d80-3b6f-11ea-9452-efcade557cb8.png">
<img width="1552" alt="Screen Shot 2020-01-20 at 10 26 02 AM" src="https://user-images.githubusercontent.com/776780/72694349-a8f10d80-3b6f-11ea-8007-f2ed4f9d6f95.png">
