### ISSUE TITLE
Identifying Transit Stops

### ISSUE THREAD

**Issue by babakdorji** [conveyal/analysis-ui#986]
Is it possible that when you select the transit station stop, to identify the name/cross streets and possibly the transit lines that board/alight there?

**Comment by ansoncfit** [comment]
Thanks for the suggestion, @babakdorji. In some ways, this is the inverse of #967. We should consider a rework of stop selection components that addresses both these issues.

**Comment by ansoncfit** [comment]
https://github.com/conveyal/analysis-ui/pull/1369 adds a tooltip to stops during selection in reroute modifications. Further changes to stop selection pending in #967.
