### ISSUE TITLE
Clarify opportunity data management options

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#988]
I've found the terminology around managing opportunity datasets to be fairly misleading/confusing. 

![Screenshot_2020-01-23_19-48-47](https://user-images.githubusercontent.com/7830465/73036404-75d1a700-3e19-11ea-8271-b5355ff97c66.png)

"Dataset" is used to mean two different things here and the distinction between a "dataset" and a "dataset source" is not clear. There are two basic objects in play here: a spatial dataset and the variables associated with it. You can edit the names of the variables and delete them. And you can delete the whole spatial dataset along with all associated variables. 

I would suggest that the terminology on these buttons be changed as follows:
* _Upload a new dataset_ -> Upload a new spatial dataset
* _Fetch LODES (2015)_ -> (no change)
* _Edit dataset name_ -> Edit selected variable name
* _Delete this dataset_ -> Delete selected variable
* _Delete entire dataset source_ -> Delete entire spatial dataset

Though that last one still wouldn't be clear since it's not totally obvious which dataset is selected. Only the variable name is shown and the popup are-you-sure message doesn't give the name either. The easiest thing would probably be to add the name of the spatial dataset to the pop-up.

The terminology on the Analysis tab is fairly intuitive already IMO since both the spatial dataset name and the variable name are kept together.

**Comment by Nate-Wessel** [comment]
This is related to #510 which, though closed, still seems pretty relevant!

**Comment by ansoncfit** [comment]
We've discussed moving from "opportunity datasets" to "spatial layers" or similar.

When we make that change, we could clarify dataset and dataset source, maybe using "layer" and "all layers from this source"
