### ISSUE TITLE
Bona fide stops have incorrect direction indicators when following streets

### ISSUE THREAD

**Issue by mattwigway** [conveyal/analysis-ui#99]
I think this is because the stop isn't quite on the road, so there is a short segment connecting it to the road. I'm thinking maybe we should just snap to the roads?

![image](https://cloud.githubusercontent.com/assets/566958/15539855/d7730ecc-2252-11e6-9624-d38d72d91cf9.png)

**Comment by trevorgerhardt** [comment]
I don't believe this problem exists anymore. If it does please re-open with a specific way of reproducing.
