### ISSUE TITLE
Possible backwards travel on directed trip pattern

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#993]
I've created a phased, branching service into an area not otherwise served by transit. Neither branch of the service is bidirectional, but it seems that there may be some slight backwards travel happening at times. 

![Screenshot_2020-01-26_13-16-18](https://user-images.githubusercontent.com/7830465/73139646-1c968d00-403e-11ea-8147-15ad06ce1ae4.png)

When comparing the baseline to the scenario with the modifications, I sometimes get the expected result at the end of the line where both isochrones are identical. 

![Screenshot_2020-01-26_13-19-29](https://user-images.githubusercontent.com/7830465/73139699-b1998600-403e-11ea-90cc-241ff90d8401.png)

or where the line goes forward but not back. 

![Screenshot_2020-01-26_13-22-08](https://user-images.githubusercontent.com/7830465/73139722-eefe1380-403e-11ea-9c37-8e2be2a4ee81.png)

Other times, it seems like there is some definite backwards transit travel relative to the baseline scenario. 

![Screenshot_2020-01-26_13-26-40](https://user-images.githubusercontent.com/7830465/73139787-9bd89080-403f-11ea-972f-973e5f116ee5.png)
In this case, it's reasonable to be able to walk north to the transfer point and catch the other branch westbound, but there should be no advantage at all for northbound travel relative to the baseline scenario. 

One more example:

![Screenshot_2020-01-26_13-30-54](https://user-images.githubusercontent.com/7830465/73139848-549ecf80-4040-11ea-9295-99f26120a1f3.png)

The project is at: https://analysis-staging.conveyal.com/regions/5e2dc25a7d0f5225fe06962c/analysis?projectId=5e2dc3d97d0f5225fe06963a

**Comment by ansoncfit** [comment]
At first glance, my guess is this relates to walking limits. By default, each leg (access, transfer, egress) is limited to a 20 minute walk (though this isn't shown in the UI).

In the 4th image above, I bet someone can walk to the northernmost stop in purple in just under 20 minutes, then ride 1 stop south (in the correct direction), then walk 20 (more) minutes north.

Could you confirm by adjusting the Max Walk Time value?

**Comment by Nate-Wessel** [comment]
@ansoncfit I think you're right.
If this is expected behaviour, I wonder if we should document it somewhere as a possible edge case?

**Comment by ansoncfit** [comment]
Sure, it would be good to expand slightly the discussion of the access/egress/transfer leg time limits at http://docs.analysis.conveyal.com/en/latest/analysis/index.html#advanced-settings

**Comment by Nate-Wessel** [comment]
@ansoncfit that section seems to be gone from the latest version of the documentation. I can't find any mention of legs or walk time settings at all actually. When was that page last updated?

**Comment by ansoncfit** [comment]
@Nate-Wessel I merged this update directly to the master branch instead of the dev branch. You could `cherry-pick` https://github.com/conveyal/analysis-ui/commit/6983722bd74c180c6deb428da48e277f621c38ab
